import * as THREE from 'three';

// ──────────────────────────────────────────────────────────────────────
// Era Palette & Material Convention Helpers
// ──────────────────────────────────────────────────────────────────────
//
// Each era module (1945, 1960, 1980, 2000, 2025) MUST follow this
// shared palette/material convention:
//
//   1. Export a `getPalette()` function returning an object with
//      named colour tokens keyed for brick, stone, metal, glass,
//      sky, atmosphere, and accent colours.
//
//   2. Export material-construction helpers (`brickMaterial`,
//      `stoneMaterial`, `metalMaterial`, etc.) that accept a
//      condition factor (0-1) and return ready-to-use
//      THREE.MeshStandardMaterial instances pre-tinted to the
//      era's palette tokens.
//
//   3. Export any era-specific atmospheric or overlay helpers
//      (e.g., soot grime tint, coal-smoke haze map).
//
// Sibling-era agents should import these helpers and adapt the
// colour values to their period; do NOT edit this file after 1945
// is implemented — the pattern itself is the contract.
// ──────────────────────────────────────────────────────────────────────

// ── Shared base palette helper (default: 1945 reference) ───────────

/**
 * Return the default era colour palette.
 * Override per-era by spreading overrides into the returned object.
 *
 * @example
 * // In src/eras/1960.ts
 * const palette = { ...getEraPalette(), brick: 0xC4A882 };
 */
export function getEraPalette(): Record<string, number> {
  return {
    // Brick tones
    brickRed: 0x8B3A2A,
    brickBrown: 0x6B4226,
    brickDark: 0x4A2A18,
    // Stone tones
    stoneLight: 0xD4C8B0,
    stoneMedium: 0xA89878,
    stoneDark: 0x7A6E58,
    // Metal tones
    ironDark: 0x2A2A2A,
    steelGrey: 0x5A5A5A,
    chromeAccent: 0xAAAAAA,
    copper: 0xB87333,
    // Glass tones
    windowGlass: 0x8899AA,
    dirtyGlass: 0x667766,
    // Atmosphere / overlay
    coalSmoke: 0x3A3A3A,
    sootGrime: 0x2D2520,
    sepiaTint: 0xC8A870,
    warmSun: 0xFFDDAA,
    mutedSky: 0x8899AA,
    // Ground / pavement
    asphalt: 0x444440,
    concrete: 0x999990,
    wood: 0x6B4226,
    // Accent paints
    paintRed: 0xCC3333,
    paintBlue: 0x2244AA,
    paintGreen: 0x225533,
    paintYellow: 0xCCBB44,
  };
}

// ── Material construction helpers ──────────────────────────────────

/**
 * Construct a brick wall material tinted to the era palette.
 * The roughness increases slightly with age (lower condition).
 *
 * @param condition - Wear factor 0..1 (1 = new)
 * @param palette   - Era palette from getEraPalette()
 * @returns THREE.MeshStandardMaterial ready for use on walls
 */
export function brickMaterial(condition: number, palette?: Record<string, number>): THREE.MeshStandardMaterial {
  const p = palette || getEraPalette();
  const c = new THREE.Color(p.brickRed);
  // Desaturate slightly for older condition
  const desat = 1 - (1 - condition) * 0.15;
  c.multiplyScalar(desat);
  return new THREE.MeshStandardMaterial({
    color: c,
    roughness: 0.85 - condition * 0.15,
    metalness: 0.0,
  });
}

/**
 * Construct a stone wall material.
 *
 * @param condition - Wear factor 0..1
 * @param palette   - Era palette
 * @returns THREE.MeshStandardMaterial for stone surfaces
 */
export function stoneMaterial(condition: number, palette?: Record<string, number>): THREE.MeshStandardMaterial {
  const p = palette || getEraPalette();
  return new THREE.MeshStandardMaterial({
    color: new THREE.Color(p.stoneMedium),
    roughness: 0.9 - condition * 0.1,
    metalness: 0.0,
  });
}

/**
 * Construct cast-iron / dark metal material.
 * Used for lamp posts, hydrants, fire escapes, railings.
 */
export function ironMaterial(condition: number, palette?: Record<string, number>): THREE.MeshStandardMaterial {
  const p = palette || getEraPalette();
  const base = new THREE.Color(p.ironDark);
  const shade = 0.1 + (1 - condition) * 0.08;
  return new THREE.MeshStandardMaterial({
    color: base.clone().lerp(new THREE.Color(0xFFFFFF), shade),
    roughness: 0.7,
    metalness: 0.6,
  });
}

/**
 * Construct weathered steel/grey metal material.
 * Used for water tanks, gutters, trim.
 */
export function steelMaterial(condition: number, palette?: Record<string, number>): THREE.MeshStandardMaterial {
  const p = palette || getEraPalette();
  const base = new THREE.Color(p.steelGrey);
  const shade = 0.3 + condition * 0.2;
  return new THREE.MeshStandardMaterial({
    color: base.clone().lerp(new THREE.Color(0xFFFFFF), shade),
    roughness: 0.6,
    metalness: 0.5,
  });
}

/**
 * Construct window glass material.
 * Condition affects clarity and opacity.
 */
export function glassMaterial(condition: number, palette?: Record<string, number>): THREE.MeshStandardMaterial {
  const p = palette || getEraPalette();
  const clarity = 0.2 + condition * 0.35;
  return new THREE.MeshStandardMaterial({
    color: new THREE.Color(p.windowGlass),
    transparent: true,
    opacity: clarity,
    roughness: 0.1,
    metalness: 0.1,
  });
}

/**
 * Construct a soot/grime overlay material.
 * Returns a semi-transparent dark material for applying over
 * dirty surfaces (ground floor walls, lower storey areas).
 *
 * Use as a second pass or blend over base wall materials.
 */
export function sootGrimeOverlay(condition: number, palette?: Record<string, number>): THREE.MeshBasicMaterial {
  const p = palette || getEraPalette();
  const intensity = 0.3 + (1 - condition) * 0.4;
  return new THREE.MeshBasicMaterial({
    color: new THREE.Color(p.sootGrime),
    transparent: true,
    opacity: Math.min(intensity, 0.7),
    depthWrite: false,
  });
}

/**
 * Construct a coal-smoke haze volumetric tint.
 * Returns a semi-transparent warm-grey material suitable for
 * a large sphere/plane used as atmospheric fog.
 *
 * For best results, place behind the scene with additive blending.
 */
export function coalSmokeHaze(condition: number, palette?: Record<string, number>): THREE.MeshBasicMaterial {
  const p = palette || getEraPalette();
  const density = 0.12 + (1 - condition) * 0.1;
  return new THREE.MeshBasicMaterial({
    color: new THREE.Color(p.coalSmoke),
    transparent: true,
    opacity: density,
    depthWrite: false,
    side: THREE.DoubleSide,
  });
}

/**
 * Construct a sepia-toned sun glow material.
 * Warm yellowish light for directional or point lights to
 * simulate the period-appropriate sepia-leaning sunlight.
 */
export function sepiaSunGlow(palette?: Record<string, number>): THREE.Color {
  const p = palette || getEraPalette();
  return new THREE.Color(p.warmSun);
}

/**
 * Construct muted desaturated wall paint.
 * For painted-wall advertisements and shop fronts.
 */
export function mutedPaint(tone: 'red' | 'blue' | 'green' | 'yellow' | 'cream', condition: number, palette?: Record<string, number>): THREE.MeshStandardMaterial {
  const p = palette || getEraPalette();
  const colorMap: Record<string, number> = {
    red: p.paintRed,
    blue: p.paintBlue,
    green: p.paintGreen,
    yellow: p.paintYellow,
    cream: p.stoneLight,
  };
  const raw = new THREE.Color(colorMap[tone]);
  // Desaturate for period-muted look
  const hsl = {};
  raw.getHSL(hsl as any);
  const hue = (raw as any)._h;
  const sat = ((raw as any)._s || 0.5) * 0.6;
  const lit = ((raw as any)._l || 0.5) * (0.7 + condition * 0.3);
  raw.setHSL(hue, sat, lit);
  return new THREE.MeshStandardMaterial({
    color: raw,
    roughness: 0.75 - condition * 0.1,
    metalness: 0.0,
  });
}
