/**
 * The shipped era table: one complete record per time period.
 *
 * This file is the single source of truth for the timeline. Everything the
 * scene changes when the slider moves is a value here, so the registry, the
 * store and every content layer stay free of `year === 1985` style branching.
 *
 * Adding the 2055 period that README.md mentions is a data-only change:
 * append `'2055'` to `ERA_IDS`, add its year mapping, add the year to
 * `ERA_YEARS`, and add one record below. No code path needs to know.
 */

import { ERA_IDS, ERA_YEAR_BY_ID } from './eraIds'
import type { EraId } from './eraIds'
import { ERA_SOUNDSCAPES } from './soundscape'
import type { EraDefinition } from './types'

const ERA_TABLE: Readonly<Record<EraId, EraDefinition>> = {
  '1945': {
    id: '1945',
    year: 1945,
    shortLabel: '1945',
    label: 'Postwar Recovery',
    summary:
      'Victory banners over a soot-stained block: drab brick, enamel signs, rationed traffic and coal smoke in the air.',
    seed: 'city-era-1945',
    palette: {
      buildingBase: '#6b5946',
      buildingAccent: '#4a3d31',
      facadeTrim: '#cbbfa4',
      windowGlass: '#2f3a3a',
      roadSurface: '#3a3733',
      roadMarking: '#c9c2a6',
      sidewalk: '#8a8478',
      storefrontBody: '#33402f',
      storefrontSign: '#e4d9b8',
      streetFurniture: '#2a2c2a',
      accent: '#8c3b2a',
    },
    lighting: {
      timeOfDayHours: 16.6,
      sunAzimuthDeg: 245,
      sunElevationDeg: 14,
      sunColor: '#ffc98a',
      sunIntensity: 0.85,
      skyTopColor: '#7b8794',
      skyHorizonColor: '#d9c3a3',
      ambientColor: '#8a8578',
      ambientIntensity: 0.32,
      hemisphereIntensity: 0.4,
      artificialLightColor: '#ffb469',
      artificialLightIntensity: 0.35,
      exposure: 0.92,
      shadowSoftness: 0.6,
    },
    atmosphere: {
      hazeColor: '#c2b191',
      hazeDensity: 0.028,
      hazeHeightFalloff: 0.35,
      cloudCover: 0.78,
      precipitation: 'drizzle',
      precipitationIntensity: 0.18,
      particleDensity: 0.55,
      windSpeedMps: 3.4,
      colourGrade: {
        lift: [0.02, 0.014, 0.006],
        gamma: [1.02, 1, 0.94],
        gain: [0.98, 0.94, 0.86],
        saturation: 0.72,
        contrast: 1.04,
        temperature: 0.18,
        tint: -0.04,
        vignette: 0.34,
        grain: 0.42,
        bloomIntensity: 0.12,
        bloomThreshold: 0.86,
      },
    },
    soundscape: ERA_SOUNDSCAPES['1945'],
    traffic: {
      vehicleEraTag: '1945-postwar-sedan',
      trafficDensity: 0.12,
      averageSpeedMps: 5.2,
      laneCount: 2,
      parkedRatio: 0.55,
      headlightIntensity: 0.5,
      hornProbability: 0.04,
      modelKeys: ['sedan-1940s', 'panel-van-1940s', 'tram-car-1930s', 'army-surplus-truck'],
    },
    population: {
      outfitEraTag: '1945-wool-overcoat',
      pedestrianDensity: 0.35,
      averageSpeedMps: 1.05,
      groupSizeRange: [1, 2],
      childRatio: 0.14,
      outfitPalette: ['#3d3a33', '#5b5346', '#7a6a52', '#2f3a46', '#8c3b2a'],
      modelKeys: [
        'worker-overcoat',
        'ration-shopper',
        'newsboy-cap',
        'homemaker-dress',
        'returning-soldier',
      ],
    },
    contentTags: {
      signage: [
        'hand-lettered',
        'enamel-porcelain',
        'painted-brick-wall',
        'channel-glass',
        'war-bond-notice',
      ],
      advertisements: ['war-bonds', 'lucky-strike', 'coca-cola', 'ford-v8', 'wrigley-spearmint'],
      storefronts: ['butcher', 'barber', 'pharmacy-soda-fountain', 'haberdasher', 'hardware'],
      buildings: [
        'brownstone',
        'soot-brick-warehouse',
        'tenement-fire-escape',
        'corner-bank',
        'cast-iron-loft',
      ],
      props: ['cast-iron-lamp', 'fire-hydrant', 'news-stand', 'milk-crate', 'coal-chute'],
    },
  },
  '1965': {
    id: '1965',
    year: 1965,
    shortLabel: '1965',
    label: 'Mid-Century Boom',
    summary:
      'Chrome, pastel panels and tailfin sedans under a hard blue sky: the block rebuilt for the automobile.',
    seed: 'city-era-1965',
    palette: {
      buildingBase: '#9aa3a0',
      buildingAccent: '#5f7f86',
      facadeTrim: '#e8e3d6',
      windowGlass: '#5d7f8c',
      roadSurface: '#4a4a4c',
      roadMarking: '#e8c63f',
      sidewalk: '#b2ada0',
      storefrontBody: '#c94f3d',
      storefrontSign: '#f2f0e4',
      streetFurniture: '#8d949c',
      accent: '#2f8f86',
    },
    lighting: {
      timeOfDayHours: 12.4,
      sunAzimuthDeg: 180,
      sunElevationDeg: 58,
      sunColor: '#fff4d6',
      sunIntensity: 1.35,
      skyTopColor: '#3f8fd6',
      skyHorizonColor: '#cfe6f5',
      ambientColor: '#9dc0e0',
      ambientIntensity: 0.45,
      hemisphereIntensity: 0.6,
      artificialLightColor: '#fff3cf',
      artificialLightIntensity: 0.12,
      exposure: 1.05,
      shadowSoftness: 0.3,
    },
    atmosphere: {
      hazeColor: '#cfe0ea',
      hazeDensity: 0.014,
      hazeHeightFalloff: 0.5,
      cloudCover: 0.22,
      precipitation: 'none',
      precipitationIntensity: 0,
      particleDensity: 0.22,
      windSpeedMps: 4.2,
      colourGrade: {
        lift: [0.01, 0.008, 0.012],
        gamma: [1, 1, 1.02],
        gain: [1.04, 1.03, 0.99],
        saturation: 1.18,
        contrast: 1.1,
        temperature: 0.05,
        tint: 0.02,
        vignette: 0.2,
        grain: 0.18,
        bloomIntensity: 0.25,
        bloomThreshold: 0.8,
      },
    },
    soundscape: ERA_SOUNDSCAPES['1965'],
    traffic: {
      vehicleEraTag: '1965-tailfin-sedan',
      trafficDensity: 0.44,
      averageSpeedMps: 9.5,
      laneCount: 4,
      parkedRatio: 0.38,
      headlightIntensity: 0.2,
      hornProbability: 0.18,
      modelKeys: [
        'tailfin-sedan-1960s',
        'muscle-coupe-1965',
        'city-bus-1960s',
        'delivery-van-1960s',
        'motor-scooter-1960s',
      ],
    },
    population: {
      outfitEraTag: '1965-clean-cut-suit',
      pedestrianDensity: 0.62,
      averageSpeedMps: 1.3,
      groupSizeRange: [1, 3],
      childRatio: 0.22,
      outfitPalette: ['#2f4f6f', '#c94f3d', '#e8d36a', '#5f8f5a', '#f0e6d2'],
      modelKeys: [
        'suit-and-fedora',
        'shift-dress',
        'turtleneck-beatnik',
        'student-cardigan',
        'bus-driver-uniform',
      ],
    },
    contentTags: {
      signage: [
        'neon-script',
        'plastic-backlit-box',
        'googie-arrow',
        'painted-bulletin',
        'chase-light-marquee',
      ],
      advertisements: ['coca-cola', 'pepsi-generation', 'sinclair-dino', 'ford-mustang', 'rca-color-tv'],
      storefronts: ['diner', 'department-store', 'gas-station', 'bowling-alley', 'record-shop'],
      buildings: [
        'glass-curtain-tower',
        'precast-concrete-office',
        'googie-motel',
        'brick-apartment-1960s',
        'parking-garage',
      ],
      props: ['traffic-light-1960s', 'parking-meter', 'telephone-booth', 'bus-shelter', 'neon-arrow-sign'],
    },
  },
  '1985': {
    id: '1985',
    year: 1985,
    shortLabel: '1985',
    label: 'Neon Downtown',
    summary:
      'Wet asphalt, neon reflections and glowing arcades: smog-dusk over a downtown built on cars and cathode tubes.',
    seed: 'city-era-1985',
    palette: {
      buildingBase: '#5a5c63',
      buildingAccent: '#2e5a7a',
      facadeTrim: '#8e8f96',
      windowGlass: '#1d3a4a',
      roadSurface: '#2f3034',
      roadMarking: '#d8d24a',
      sidewalk: '#6e6f74',
      storefrontBody: '#2b2d3a',
      storefrontSign: '#ff4fa3',
      streetFurniture: '#3c3f46',
      accent: '#31e0d8',
    },
    lighting: {
      timeOfDayHours: 19.9,
      sunAzimuthDeg: 300,
      sunElevationDeg: -3,
      sunColor: '#8a5fbf',
      sunIntensity: 0.18,
      skyTopColor: '#171a33',
      skyHorizonColor: '#b4447a',
      ambientColor: '#3c3a5c',
      ambientIntensity: 0.5,
      hemisphereIntensity: 0.35,
      artificialLightColor: '#ff3ea5',
      artificialLightIntensity: 1.25,
      exposure: 1.15,
      shadowSoftness: 0.75,
    },
    atmosphere: {
      hazeColor: '#3a2a4a',
      hazeDensity: 0.042,
      hazeHeightFalloff: 0.28,
      cloudCover: 0.45,
      precipitation: 'rain',
      precipitationIntensity: 0.35,
      particleDensity: 0.5,
      windSpeedMps: 2.8,
      colourGrade: {
        lift: [0.03, 0.012, 0.04],
        gamma: [0.96, 0.98, 1.06],
        gain: [1.06, 0.96, 1.12],
        saturation: 1.32,
        contrast: 1.18,
        temperature: -0.12,
        tint: 0.16,
        vignette: 0.42,
        grain: 0.36,
        bloomIntensity: 0.72,
        bloomThreshold: 0.62,
      },
    },
    soundscape: ERA_SOUNDSCAPES['1985'],
    traffic: {
      vehicleEraTag: '1985-boxy-hatchback',
      trafficDensity: 0.68,
      averageSpeedMps: 10.8,
      laneCount: 4,
      parkedRatio: 0.46,
      headlightIntensity: 1,
      hornProbability: 0.3,
      modelKeys: [
        'hatchback-1980s',
        'box-truck-1980s',
        'checker-taxi-1985',
        'police-cruiser-1985',
        'bmx-bike-1985',
      ],
    },
    population: {
      outfitEraTag: '1985-neon-streetwear',
      pedestrianDensity: 0.78,
      averageSpeedMps: 1.18,
      groupSizeRange: [1, 4],
      childRatio: 0.16,
      outfitPalette: ['#ff4fa3', '#31e0d8', '#f5f0c8', '#3b3f8f', '#d94f2b'],
      modelKeys: [
        'denim-jacket',
        'tracksuit',
        'shoulder-pad-blazer',
        'punk-mohawk',
        'boom-box-carrier',
      ],
    },
    contentTags: {
      signage: [
        'neon-tube',
        'backlit-plastic-box',
        'chase-bulb',
        'handwritten-flyer',
        'vinyl-window-decal',
      ],
      advertisements: [
        'pepsi-michael-jackson',
        'apple-macintosh',
        'nike-swoosh',
        'mtv-logo',
        'coca-cola-classic',
      ],
      storefronts: ['arcade', 'video-rental', 'pizza-parlour', 'convenience-store', 'record-and-tape'],
      buildings: [
        'mirror-glass-tower',
        'postmodern-pink-concrete',
        'brick-warehouse-loft',
        'strip-mall',
        'parking-garage-1980s',
      ],
      props: ['boom-box', 'payphone', 'neon-palm-sign', 'dumpster', 'bmx-rack'],
    },
  },
  '2005': {
    id: '2005',
    year: 2005,
    shortLabel: '2005',
    label: 'Digital Turn',
    summary:
      'Brushed aluminium, glass lobbies and orange signage: a clean, overcast downtown wired for the web and the SUV.',
    seed: 'city-era-2005',
    palette: {
      buildingBase: '#a8adb4',
      buildingAccent: '#5a6470',
      facadeTrim: '#d8dce0',
      windowGlass: '#4e6b7c',
      roadSurface: '#3c3f45',
      roadMarking: '#e6e6e6',
      sidewalk: '#9b9ea3',
      storefrontBody: '#7d8794',
      storefrontSign: '#e8642c',
      streetFurniture: '#6f757c',
      accent: '#1f7ae0',
    },
    lighting: {
      timeOfDayHours: 10.5,
      sunAzimuthDeg: 135,
      sunElevationDeg: 44,
      sunColor: '#ffffff',
      sunIntensity: 1.05,
      skyTopColor: '#8fa9c4',
      skyHorizonColor: '#e2e6ea',
      ambientColor: '#a9b4c0',
      ambientIntensity: 0.5,
      hemisphereIntensity: 0.55,
      artificialLightColor: '#fff1e0',
      artificialLightIntensity: 0.22,
      exposure: 1,
      shadowSoftness: 0.45,
    },
    atmosphere: {
      hazeColor: '#c8d2da',
      hazeDensity: 0.02,
      hazeHeightFalloff: 0.42,
      cloudCover: 0.55,
      precipitation: 'none',
      precipitationIntensity: 0,
      particleDensity: 0.3,
      windSpeedMps: 5.1,
      colourGrade: {
        lift: [0.008, 0.01, 0.014],
        gamma: [1.06, 1.03, 0.99],
        gain: [0.99, 1, 1.05],
        saturation: 1.06,
        contrast: 1.12,
        temperature: -0.06,
        tint: 0.05,
        vignette: 0.22,
        grain: 0.14,
        bloomIntensity: 0.35,
        bloomThreshold: 0.78,
      },
    },
    soundscape: ERA_SOUNDSCAPES['2005'],
    traffic: {
      vehicleEraTag: '2005-silver-suv',
      trafficDensity: 0.82,
      averageSpeedMps: 11.6,
      laneCount: 5,
      parkedRatio: 0.52,
      headlightIntensity: 0.35,
      hornProbability: 0.22,
      modelKeys: [
        'compact-sedan-2000s',
        'suv-2000s',
        'sprinter-van-2000s',
        'city-bus-2000s',
        'courier-bike-2000s',
      ],
    },
    population: {
      outfitEraTag: '2005-low-rise-denim',
      pedestrianDensity: 0.86,
      averageSpeedMps: 1.32,
      groupSizeRange: [1, 3],
      childRatio: 0.2,
      outfitPalette: ['#2b3a55', '#d9d5cd', '#c94f3d', '#5f7f5a', '#202124'],
      modelKeys: [
        'hoodie-and-jeans',
        'business-casual',
        'puffer-jacket',
        'school-backpack',
        'barista-apron',
      ],
    },
    contentTags: {
      signage: ['led-matrix', 'acrylic-lightbox', 'vehicle-wrap', 'vinyl-plotter', 'projected-gobo'],
      advertisements: [
        'ipod-silhouette',
        'motorola-razr',
        'starbucks-mermaid',
        'nike-run',
        'honda-civic',
      ],
      storefronts: [
        'coffee-chain',
        'internet-cafe',
        'cell-phone-store',
        'copy-shop',
        'fast-casual-salad',
      ],
      buildings: [
        'glass-and-steel-tower',
        'postmodern-stucco',
        'loft-conversion',
        'big-box-strip-mall',
        'transit-hub',
      ],
      props: ['bus-shelter-ad', 'parking-kiosk', 'security-camera', 'bike-rack', 'atm'],
    },
  },
  '2025': {
    id: '2025',
    year: 2025,
    shortLabel: '2025',
    label: 'Electric Present',
    summary:
      'Warm low sun on mass timber and solar glass: quiet EVs, cargo bikes and contactless signage on a greened curb.',
    seed: 'city-era-2025',
    palette: {
      buildingBase: '#8d8a86',
      buildingAccent: '#3f4a52',
      facadeTrim: '#e6e2da',
      windowGlass: '#6d8f9c',
      roadSurface: '#33363b',
      roadMarking: '#f0d24a',
      sidewalk: '#a9a49b',
      storefrontBody: '#1f6f5a',
      storefrontSign: '#f5f2ea',
      streetFurniture: '#4a4f52',
      accent: '#2fb6ff',
    },
    lighting: {
      timeOfDayHours: 18.2,
      sunAzimuthDeg: 264,
      sunElevationDeg: 11,
      sunColor: '#ffd9a0',
      sunIntensity: 0.95,
      skyTopColor: '#6f9fd8',
      skyHorizonColor: '#f2c99a',
      ambientColor: '#9aa7b0',
      ambientIntensity: 0.42,
      hemisphereIntensity: 0.5,
      artificialLightColor: '#d8f0ff',
      artificialLightIntensity: 0.85,
      exposure: 1.02,
      shadowSoftness: 0.5,
    },
    atmosphere: {
      hazeColor: '#c9c2b6',
      hazeDensity: 0.017,
      hazeHeightFalloff: 0.48,
      cloudCover: 0.3,
      precipitation: 'none',
      precipitationIntensity: 0,
      particleDensity: 0.26,
      windSpeedMps: 3.9,
      colourGrade: {
        lift: [0.012, 0.014, 0.02],
        gamma: [1, 1.01, 1.04],
        gain: [1.05, 1.01, 0.94],
        saturation: 0.98,
        contrast: 1.14,
        temperature: 0.09,
        tint: -0.02,
        vignette: 0.26,
        grain: 0.1,
        bloomIntensity: 0.45,
        bloomThreshold: 0.74,
      },
    },
    soundscape: ERA_SOUNDSCAPES['2025'],
    traffic: {
      vehicleEraTag: '2025-electric-crossover',
      trafficDensity: 0.58,
      averageSpeedMps: 9.8,
      laneCount: 4,
      parkedRatio: 0.6,
      headlightIntensity: 1.15,
      hornProbability: 0.05,
      modelKeys: [
        'electric-crossover',
        'electric-city-bus',
        'cargo-e-bike',
        'delivery-van-2025',
        'robotaxi-pod',
      ],
    },
    population: {
      outfitEraTag: '2025-layered-streetwear',
      pedestrianDensity: 0.95,
      averageSpeedMps: 1.42,
      groupSizeRange: [1, 3],
      childRatio: 0.18,
      outfitPalette: ['#1f2a33', '#f2ede4', '#2fb6ff', '#e0a24a', '#5a6b5f'],
      modelKeys: [
        'puffer-mid-layer',
        'athleisure-set',
        'delivery-courier',
        'student-hoodie',
        'smart-casual-office',
      ],
    },
    contentTags: {
      signage: [
        'led-video-wall',
        'digital-menu-board',
        'projected-logo',
        'qr-postcard',
        'chalkboard-artisan',
      ],
      advertisements: [
        'streaming-billboard',
        'ev-charging-network',
        'electric-suv',
        'fintech-app',
        'plant-based-burger',
      ],
      storefronts: [
        'specialty-coffee',
        'boba-tea',
        'grocery-cooperative',
        'e-bike-rental',
        'co-working-lobby',
      ],
      buildings: [
        'mass-timber-office',
        'glass-curtain-wall-2020s',
        'adaptive-reuse-brick',
        'modular-micro-unit',
        'transit-oriented-podium',
      ],
      props: ['ev-charger', 'e-scooter-rack', 'parklet-bench', 'smart-bus-shelter', 'air-quality-sensor'],
    },
  },
}

/**
 * Guards the era table at module load: every required id is present, its key
 * matches the record's own id, and the declared year matches the id mapping.
 */
function defineEraTable(
  table: Readonly<Record<EraId, EraDefinition>>,
): Readonly<Record<EraId, EraDefinition>> {
  for (const id of ERA_IDS) {
    const definition = table[id]
    if (definition === undefined) {
      throw new Error(`The era table is missing a record for '${id}'.`)
    }
    if (definition.id !== id) {
      throw new Error(`The era record keyed '${id}' declares id '${definition.id}'.`)
    }
    if (definition.year !== ERA_YEAR_BY_ID[id]) {
      throw new Error(
        `Era '${id}' declares year ${definition.year} but its id maps to ${ERA_YEAR_BY_ID[id]}.`,
      )
    }
  }
  return Object.freeze(table)
}

/**
 * Every shipped era, keyed by id.
 *
 * This is the raw data table; {@link ERA_REGISTRY} adds ordering, lookup and
 * neighbour helpers on top of it.
 */
export const ERA_RECORDS: Readonly<Record<EraId, EraDefinition>> = defineEraTable(ERA_TABLE)
