/**
 * Per-era soundscape descriptors.
 *
 * Each era owns a sonic identity: an ambient bed, a music bed, a tempo/key for
 * the transition director to cross-fade around, and the cue list the audio
 * engine builds its layers from. Keeping the data here (rather than inline in
 * the era records) lets the audio task iterate on sound design without touching
 * the palette, lighting or traffic data.
 */

import { requireEraId } from './eraIds'
import type { EraId } from './eraIds'
import type { EraSoundscape } from './types'

const SOUNDSCAPES: Readonly<Record<EraId, EraSoundscape>> = {
  '1945': {
    descriptor: '1945-home-front',
    label: 'Home Front Hum',
    ambienceGain: 0.55,
    musicGain: 0.2,
    tempoBpm: 68,
    key: 'D minor',
    reverbDecaySec: 1.1,
    cues: [
      {
        id: 'tram-bell',
        label: 'Tram bell on the corner',
        layer: 'signature',
        gain: 0.5,
        loop: false,
        minIntervalSec: 12,
        maxIntervalSec: 34,
      },
      {
        id: 'coal-truck-idle',
        label: 'Coal truck idling',
        layer: 'engine',
        gain: 0.42,
        loop: true,
        minIntervalSec: 18,
        maxIntervalSec: 46,
      },
      {
        id: 'newsboy-call',
        label: 'Newsboy calling headlines',
        layer: 'human',
        gain: 0.36,
        loop: false,
        minIntervalSec: 20,
        maxIntervalSec: 55,
      },
      {
        id: 'radio-ballroom',
        label: 'Radio ballroom through an open window',
        layer: 'music',
        gain: 0.28,
        loop: true,
        minIntervalSec: 40,
        maxIntervalSec: 90,
      },
      {
        id: 'soda-fountain-clatter',
        label: 'Soda fountain clatter',
        layer: 'human',
        gain: 0.3,
        loop: false,
        minIntervalSec: 14,
        maxIntervalSec: 40,
      },
      {
        id: 'steam-radiator-hiss',
        label: 'Steam and radiator hiss',
        layer: 'ambience',
        gain: 0.34,
        loop: true,
        minIntervalSec: 22,
        maxIntervalSec: 60,
      },
    ],
  },
  '1965': {
    descriptor: '1965-mid-century-boom',
    label: 'Mid-Century Boom',
    ambienceGain: 0.6,
    musicGain: 0.3,
    tempoBpm: 104,
    key: 'C major',
    reverbDecaySec: 0.9,
    cues: [
      {
        id: 'v8-idle-rumble',
        label: 'V8 idle at the kerb',
        layer: 'engine',
        gain: 0.5,
        loop: true,
        minIntervalSec: 8,
        maxIntervalSec: 26,
      },
      {
        id: 'traffic-light-buzzer',
        label: 'Mechanical traffic-light buzzer',
        layer: 'machine',
        gain: 0.3,
        loop: false,
        minIntervalSec: 16,
        maxIntervalSec: 38,
      },
      {
        id: 'diners-jukebox',
        label: 'Diner jukebox',
        layer: 'music',
        gain: 0.38,
        loop: true,
        minIntervalSec: 26,
        maxIntervalSec: 62,
      },
      {
        id: 'department-store-muzak',
        label: 'Department-store muzak',
        layer: 'music',
        gain: 0.26,
        loop: true,
        minIntervalSec: 45,
        maxIntervalSec: 95,
      },
      {
        id: 'pneumatic-drill',
        label: 'Construction pneumatic drill',
        layer: 'machine',
        gain: 0.44,
        loop: true,
        minIntervalSec: 30,
        maxIntervalSec: 75,
      },
      {
        id: 'ice-cream-truck-chime',
        label: 'Ice-cream truck chime',
        layer: 'signature',
        gain: 0.4,
        loop: false,
        minIntervalSec: 60,
        maxIntervalSec: 150,
      },
    ],
  },
  '1985': {
    descriptor: '1985-neon-downtown',
    label: 'Neon Downtown',
    ambienceGain: 0.7,
    musicGain: 0.45,
    tempoBpm: 124,
    key: 'A minor',
    reverbDecaySec: 1.4,
    cues: [
      {
        id: 'arcade-bleeps',
        label: 'Arcade cabinet bleeps',
        layer: 'machine',
        gain: 0.48,
        loop: true,
        minIntervalSec: 5,
        maxIntervalSec: 18,
      },
      {
        id: 'synth-bassline',
        label: 'Synth bassline from a car stereo',
        layer: 'music',
        gain: 0.5,
        loop: true,
        minIntervalSec: 10,
        maxIntervalSec: 30,
      },
      {
        id: 'distant-siren',
        label: 'Distant police siren',
        layer: 'signature',
        gain: 0.4,
        loop: false,
        minIntervalSec: 24,
        maxIntervalSec: 70,
      },
      {
        id: 'cassette-hiss',
        label: 'Cassette hiss',
        layer: 'ambience',
        gain: 0.22,
        loop: true,
        minIntervalSec: 35,
        maxIntervalSec: 80,
      },
      {
        id: 'traffic-horn-queue',
        label: 'Gridlocked traffic horns',
        layer: 'engine',
        gain: 0.46,
        loop: false,
        minIntervalSec: 9,
        maxIntervalSec: 28,
      },
      {
        id: 'neon-transformer-buzz',
        label: 'Neon transformer buzz',
        layer: 'ambience',
        gain: 0.28,
        loop: true,
        minIntervalSec: 18,
        maxIntervalSec: 50,
      },
    ],
  },
  '2005': {
    descriptor: '2005-digital-turn',
    label: 'Digital Turn',
    ambienceGain: 0.62,
    musicGain: 0.38,
    tempoBpm: 96,
    key: 'F major',
    reverbDecaySec: 1,
    cues: [
      {
        id: 'mobile-ringtone',
        label: 'Mobile ringtone mosaic',
        layer: 'signature',
        gain: 0.5,
        loop: false,
        minIntervalSec: 12,
        maxIntervalSec: 40,
      },
      {
        id: 'escalator-whine',
        label: 'Escalator whine',
        layer: 'machine',
        gain: 0.34,
        loop: true,
        minIntervalSec: 20,
        maxIntervalSec: 55,
      },
      {
        id: 'cappuccino-steam',
        label: 'Cappuccino steam wand',
        layer: 'ambience',
        gain: 0.3,
        loop: false,
        minIntervalSec: 8,
        maxIntervalSec: 24,
      },
      {
        id: 'subway-announcement',
        label: 'Transit announcement',
        layer: 'signature',
        gain: 0.38,
        loop: false,
        minIntervalSec: 30,
        maxIntervalSec: 80,
      },
      {
        id: 'shop-radio-pop',
        label: 'Shop radio pop playlist',
        layer: 'music',
        gain: 0.24,
        loop: true,
        minIntervalSec: 40,
        maxIntervalSec: 90,
      },
      {
        id: 'car-alarm-chirp',
        label: 'Car alarm arming chirp',
        layer: 'machine',
        gain: 0.3,
        loop: false,
        minIntervalSec: 45,
        maxIntervalSec: 120,
      },
    ],
  },
  '2025': {
    descriptor: '2025-electric-present',
    label: 'Electric Present',
    ambienceGain: 0.52,
    musicGain: 0.34,
    tempoBpm: 88,
    key: 'G minor',
    reverbDecaySec: 1.2,
    cues: [
      {
        id: 'ev-inverter-whine',
        label: 'EV inverter whine',
        layer: 'engine',
        gain: 0.4,
        loop: true,
        minIntervalSec: 8,
        maxIntervalSec: 22,
      },
      {
        id: 'e-scooter-bell',
        label: 'E-scooter bell',
        layer: 'signature',
        gain: 0.36,
        loop: false,
        minIntervalSec: 10,
        maxIntervalSec: 32,
      },
      {
        id: 'heat-pump-hum',
        label: 'Heat-pump hum',
        layer: 'ambience',
        gain: 0.3,
        loop: true,
        minIntervalSec: 20,
        maxIntervalSec: 55,
      },
      {
        id: 'contactless-tap',
        label: 'Contactless payment taps',
        layer: 'machine',
        gain: 0.3,
        loop: false,
        minIntervalSec: 6,
        maxIntervalSec: 20,
      },
      {
        id: 'drone-delivery-buzz',
        label: 'Delivery drone buzz overhead',
        layer: 'signature',
        gain: 0.34,
        loop: false,
        minIntervalSec: 35,
        maxIntervalSec: 95,
      },
      {
        id: 'curated-playlist',
        label: 'Curated café playlist',
        layer: 'music',
        gain: 0.28,
        loop: true,
        minIntervalSec: 45,
        maxIntervalSec: 100,
      },
    ],
  },
}

/** Soundscape descriptor of every shipped era, keyed by era id. */
export const ERA_SOUNDSCAPES: Readonly<Record<EraId, EraSoundscape>> = Object.freeze(SOUNDSCAPES)

/** Soundscape of one era; throws {@link UnknownEraIdError} for unknown ids. */
export function getSoundscape(id: unknown): EraSoundscape {
  return ERA_SOUNDSCAPES[requireEraId(id)]
}
