/**
 * The storefront layer as three.js objects, plus its React host.
 *
 * {@link createStorefrontGroup} turns a {@link StorefrontPlan} into a named
 * scene graph: one group per bay anchor (frame joinery, glazing, door, awning,
 * fascia board and shutter), one mesh per advertising placement and one decal
 * per graffiti mark. Artwork is painted at runtime through the plan's
 * {@link SignSurface} descriptors — canvas textures generated by the injectable
 * factory, never image files — and *identical* artwork shares one material, so
 * a chain that repeats its sign across four bays costs one texture.
 *
 * {@link StorefrontLayer} is the React host the scene integration mounts; the
 * browser harness mounts the very same component, so the per-era proof runs the
 * shipped code.
 */

import { useEffect, useMemo, type ReactElement } from 'react'
import {
  BoxGeometry,
  BufferGeometry,
  CanvasTexture,
  Color,
  DoubleSide,
  Float32BufferAttribute,
  FrontSide,
  Group,
  Mesh,
  MeshStandardMaterial,
  PlaneGeometry,
  SRGBColorSpace,
  type Material,
  type Side,
  type Texture,
} from 'three'
import type { BlockLayout } from '../layout'
import type { EraId, HexColor } from '../../era'
import type { QualityTierName } from '../../lib/quality'
import type { Seed } from '../../lib/rng'
import { applyEra, applyEraTransition } from './index'
import { paintSignSurface } from './signage'
import { createDefaultSignCanvasFactory } from './typography'
import type {
  AnySignCanvasFactory,
  AdvertisingPlacement,
  GraffitiPlacement,
  SignSurface,
  StorefrontContext,
  StorefrontPlan,
  StorefrontTransition,
  StorefrontUnit,
  Vec3,
} from './types'
import { isIlluminationKind, isIlluminated } from './types'

/* ------------------------------------------------------------------------- *
 * Geometry helpers
 * ------------------------------------------------------------------------- */

/** One box of a merged joinery mesh, in the unit group's local space. */
interface BoxSpec {
  readonly size: readonly [number, number, number]
  readonly position: readonly [number, number, number]
}

/**
 * Merges indexed box geometries into one buffer.
 *
 * Storefront joinery is a dozen small boxes per bay; merging them keeps a
 * seventy-bay block at one draw call per bay instead of one per moulding. Only
 * position, normal and uv are carried, which is all a `MeshStandardMaterial`
 * needs.
 */
function mergeBoxes(boxes: readonly BoxSpec[]): BufferGeometry {
  const positions: number[] = []
  const normals: number[] = []
  const uvs: number[] = []
  const indices: number[] = []
  let vertexOffset = 0

  for (const box of boxes) {
    const geometry = new BoxGeometry(box.size[0], box.size[1], box.size[2])
    geometry.translate(box.position[0], box.position[1], box.position[2])
    const position = geometry.getAttribute('position')
    const normal = geometry.getAttribute('normal')
    const uv = geometry.getAttribute('uv')
    for (let index = 0; index < position.count; index += 1) {
      positions.push(position.getX(index), position.getY(index), position.getZ(index))
      normals.push(
        normal === undefined ? 0 : normal.getX(index),
        normal === undefined ? 1 : normal.getY(index),
        normal === undefined ? 0 : normal.getZ(index),
      )
      uvs.push(uv === undefined ? 0 : uv.getX(index), uv === undefined ? 0 : uv.getY(index))
    }
    const index = geometry.getIndex()
    if (index === null) {
      for (let vertex = 0; vertex < position.count; vertex += 1) {
        indices.push(vertex + vertexOffset)
      }
    } else {
      for (let vertex = 0; vertex < index.count; vertex += 1) {
        indices.push(index.getX(vertex) + vertexOffset)
      }
    }
    vertexOffset += position.count
    geometry.dispose()
  }

  const merged = new BufferGeometry()
  merged.setAttribute('position', new Float32BufferAttribute(positions, 3))
  merged.setAttribute('normal', new Float32BufferAttribute(normals, 3))
  merged.setAttribute('uv', new Float32BufferAttribute(uvs, 2))
  merged.setIndex(indices)
  merged.computeBoundingSphere()
  return merged
}

/** Converts a world point into a unit group's local space. */
export function toLocalPoint(world: Vec3, origin: Vec3, rotationY: number): readonly [number, number, number] {
  const dx = world.x - origin.x
  const dz = world.z - origin.z
  const cos = Math.cos(rotationY)
  const sin = Math.sin(rotationY)
  return [dx * cos - dz * sin, world.y - origin.y, dx * sin + dz * cos]
}

/* ------------------------------------------------------------------------- *
 * Materials
 * ------------------------------------------------------------------------- */

interface PlainMaterialOptions {
  readonly roughness?: number
  readonly metalness?: number
  readonly transparent?: boolean
  readonly opacity?: number
  readonly emissive?: HexColor
  readonly emissiveIntensity?: number
  readonly side?: Side
  readonly depthWrite?: boolean
  readonly polygonOffset?: boolean
}

/**
 * True when the painted handle is something three.js can upload.
 *
 * The painter only needs a handle with pixel dimensions, so a test double is
 * enough to build the scene graph; only a real canvas (or offscreen canvas) may
 * become a `CanvasTexture`.
 */
function isCanvasLike(value: unknown): value is HTMLCanvasElement {
  return (
    typeof value === 'object' &&
    value !== null &&
    typeof (value as { getContext?: unknown }).getContext === 'function'
  )
}

/** Material and texture cache: artwork is generated once per distinct surface. */
class StorefrontMaterialCache {
  private readonly materials = new Map<string, MeshStandardMaterial>()
  private readonly textures: Texture[] = []
  private readonly factory: AnySignCanvasFactory
  /** Colour the period's lights glow with; the era's artificial light. */
  private readonly glow: HexColor

  constructor(factory: AnySignCanvasFactory, glow: HexColor) {
    this.factory = factory
    this.glow = glow
  }

  /** Number of distinct artwork textures generated so far. */
  get textureCount(): number {
    return this.textures.length
  }

  /**
   * Material for one artwork: a canvas texture when the host can paint, a flat
   * period colour when it cannot (headless hosts keep working, unlit).
   */
  sign(surface: SignSurface, doubleSided = false): MeshStandardMaterial {
    const key = `${surface.textureKey}:${doubleSided ? 'double' : 'single'}`
    const cached = this.materials.get(key)
    if (cached !== undefined) {
      return cached
    }
    const painted = paintSignSurface(surface, this.factory)
    const material = new MeshStandardMaterial({
      color: 0xffffff,
      roughness: surface.illumination === 'painted' ? 0.85 : 0.35,
      metalness: surface.illumination === 'painted' ? 0.04 : 0.18,
      side: doubleSided ? DoubleSide : FrontSide,
    })
    const canvas = painted.canvas
    if (painted.context !== null && isCanvasLike(canvas)) {
      const texture = new CanvasTexture(canvas)
      texture.colorSpace = SRGBColorSpace
      texture.anisotropy = 2
      texture.needsUpdate = true
      this.textures.push(texture)
      material.map = texture
    } else {
      material.color = new Color(surface.background)
    }
    if (surface.emissive > 0) {
      // A lit sign emits the period's artificial light; a painted board only
      // reflects, so it keeps its own ink as the emissive tint.
      material.emissive = new Color(surface.illumination === 'painted' ? surface.ink : this.glow)
      material.emissiveIntensity = surface.emissive
      if (material.map !== null) {
        material.emissiveMap = material.map
      }
    } else {
      material.emissiveIntensity = 0
    }
    this.materials.set(key, material)
    return material
  }

  /** Graffiti decal material: the painted strokes over the wall, nothing else. */
  graffiti(surface: SignSurface, opacity: number): MeshStandardMaterial {
    const key = `${surface.textureKey}:decal`
    const cached = this.materials.get(key)
    if (cached !== undefined) {
      return cached
    }
    const material = this.sign(surface, true).clone()
    material.transparent = true
    material.opacity = opacity
    material.depthWrite = false
    material.polygonOffset = true
    material.polygonOffsetFactor = -2
    material.polygonOffsetUnits = -2
    material.roughness = 0.95
    material.metalness = 0
    material.emissiveIntensity = 0
    this.materials.set(key, material)
    return material
  }

  /** Untextured period material (joinery, door leaves, shutters, sign frames). */
  plain(key: string, colour: HexColor, options: PlainMaterialOptions = {}): MeshStandardMaterial {
    const cacheKey = `plain:${key}`
    const cached = this.materials.get(cacheKey)
    if (cached !== undefined) {
      return cached
    }
    const material = new MeshStandardMaterial({
      color: new Color(colour),
      roughness: options.roughness ?? 0.7,
      metalness: options.metalness ?? 0.1,
      transparent: options.transparent ?? false,
      opacity: options.opacity ?? 1,
      side: options.side ?? FrontSide,
      // Joinery never self-illuminates: keep the emissive channel explicit so
      // "lit" stays a property of the signage, not of three.js defaults.
      emissive: new Color(options.emissive ?? '#000000'),
      emissiveIntensity: options.emissive === undefined ? 0 : (options.emissiveIntensity ?? 0),
    })
    if (options.depthWrite !== undefined) {
      material.depthWrite = options.depthWrite
    }
    if (options.polygonOffset === true) {
      material.polygonOffset = true
      material.polygonOffsetFactor = -1
      material.polygonOffsetUnits = -1
    }
    this.materials.set(cacheKey, material)
    return material
  }

  /** Shop-interior glazing: tinted glass that glows with the era's lights. */
  glazing(plan: StorefrontPlan): MeshStandardMaterial {
    const key = `glazing:${plan.eraId}:${plan.night ? 'night' : 'day'}`
    const cached = this.materials.get(key)
    if (cached !== undefined) {
      return cached
    }
    const night = plan.night
    const material = new MeshStandardMaterial({
      color: new Color(plan.lighting.windowGlass),
      roughness: 0.08,
      metalness: 0.25,
      transparent: true,
      opacity: 0.34,
      side: DoubleSide,
      emissive: new Color(night ? plan.lighting.artificialLightColor : plan.lighting.windowGlass),
      emissiveIntensity: night ? Math.min(1, plan.lighting.artificialLightIntensity * 0.6) : 0,
    })
    this.materials.set(key, material)
    return material
  }

  dispose(): void {
    for (const material of this.materials.values()) {
      material.dispose()
    }
    for (const texture of this.textures) {
      texture.dispose()
    }
    this.materials.clear()
    this.textures.length = 0
  }
}

/* ------------------------------------------------------------------------- *
 * Object graph
 * ------------------------------------------------------------------------- */

/** Options for {@link createStorefrontGroup}. */
export interface StorefrontGroupOptions {
  /** Artwork factory; defaults to real offscreen canvases. */
  readonly canvasFactory?: AnySignCanvasFactory
  /** Light shop interiors at night (default true). */
  readonly interiors?: boolean
}

function addMesh(
  parent: Group,
  mesh: Mesh,
  name: string,
  userData: Record<string, unknown>,
): Mesh {
  mesh.name = name
  mesh.userData = userData
  parent.add(mesh)
  return mesh
}

function buildUnitGroup(
  unit: StorefrontUnit,
  plan: StorefrontPlan,
  cache: StorefrontMaterialCache,
): Group {
  const group = new Group()
  group.name = `unit:${unit.anchor}`
  group.position.set(unit.position.x, unit.position.y, unit.position.z)
  group.rotation.y = unit.rotationY
  group.userData = {
    kind: 'unit',
    anchor: unit.anchor,
    eraId: plan.eraId,
    shopType: unit.shopType,
    shopName: unit.shopName,
    street: unit.street,
  }

  const halfWidth = unit.width / 2
  const innerWidth = Math.max(0.6, unit.width - unit.frame.pilaster * 2)
  const glassHeight = Math.max(0.6, unit.glazing.headHeight - unit.glazing.sillHeight)
  const doorX = unit.door.side * (innerWidth / 2 - unit.door.width / 2)

  const frameMaterial = cache.plain(
    `frame:${plan.eraId}:${unit.frame.joinery}`,
    unit.frame.colour,
    { roughness: unit.frame.joinery === 'timber' ? 0.82 : 0.45, metalness: unit.frame.joinery === 'aluminium' ? 0.4 : 0.1 },
  )
  const boxes: BoxSpec[] = [
    {
      size: [unit.frame.pilaster, unit.height, unit.frame.depth],
      position: [-(halfWidth - unit.frame.pilaster / 2), unit.height / 2, unit.frame.depth / 2],
    },
    {
      size: [unit.frame.pilaster, unit.height, unit.frame.depth],
      position: [halfWidth - unit.frame.pilaster / 2, unit.height / 2, unit.frame.depth / 2],
    },
    {
      size: [unit.width, unit.frame.lintel, unit.frame.depth],
      position: [0, unit.height - unit.frame.lintel / 2, unit.frame.depth / 2],
    },
    {
      size: [innerWidth, unit.frame.stallRiser, unit.frame.depth],
      position: [0, unit.frame.stallRiser / 2, unit.frame.depth / 2],
    },
    {
      size: [innerWidth, unit.frame.sill, unit.frame.depth * 1.15],
      position: [0, unit.frame.stallRiser + unit.frame.sill / 2, unit.frame.depth * 0.575],
    },
    {
      size: [unit.door.width + 0.14, 0.12, unit.frame.depth],
      position: [doorX, unit.door.height + 0.06, unit.frame.depth / 2],
    },
    {
      size: [0.1, unit.door.height, unit.frame.depth],
      position: [doorX - unit.door.width / 2 - 0.06, unit.door.height / 2, unit.frame.depth / 2],
    },
    {
      size: [0.1, unit.door.height, unit.frame.depth],
      position: [doorX + unit.door.width / 2 + 0.06, unit.door.height / 2, unit.frame.depth / 2],
    },
  ]
  for (let index = 0; index < unit.glazing.mullions; index += 1) {
    const x = -innerWidth / 2 + (innerWidth * (index + 1)) / (unit.glazing.mullions + 1)
    boxes.push({
      size: [0.08, glassHeight, 0.1],
      position: [x, unit.glazing.sillHeight + glassHeight / 2, unit.frame.depth * 0.5],
    })
  }
  addMesh(group, new Mesh(mergeBoxes(boxes), frameMaterial), `${unit.anchor}:frame`, {
    kind: 'frame',
    anchor: unit.anchor,
    eraId: plan.eraId,
    joinery: unit.frame.joinery,
  })

  const glazingMaterial = cache.glazing(plan)
  addMesh(
    group,
    new Mesh(new PlaneGeometry(Math.max(0.6, innerWidth - unit.door.width * 0.35), glassHeight), glazingMaterial),
    `${unit.anchor}:glazing`,
    { kind: 'glazing', anchor: unit.anchor, eraId: plan.eraId, lit: unit.glazing.lit },
  ).position.set(0, unit.glazing.sillHeight + glassHeight / 2, -unit.glazing.inset)

  const doorMaterial = cache.plain(`door:${plan.eraId}`, unit.door.colour, {
    roughness: 0.6,
    metalness: 0.15,
  })
  const doorPanel = new Mesh(
    new BoxGeometry(unit.door.width, unit.door.height, 0.06),
    doorMaterial,
  )
  doorPanel.position.set(doorX, unit.door.height / 2, 0.05)
  addMesh(group, doorPanel, `${unit.anchor}:door`, {
    kind: 'door',
    anchor: unit.anchor,
    eraId: plan.eraId,
    glazed: unit.door.glazed,
  })
  if (unit.door.glazed) {
    const doorGlass = new Mesh(
      new PlaneGeometry(unit.door.width * 0.62, unit.door.height * 0.58),
      glazingMaterial,
    )
    doorGlass.position.set(doorX, unit.door.height * 0.58, 0.09)
    addMesh(group, doorGlass, `${unit.anchor}:door-glass`, {
      kind: 'door-glazing',
      anchor: unit.anchor,
      eraId: plan.eraId,
    })
  }

  if (unit.shutter.kind !== 'open') {
    const shutter = new Mesh(
      new BoxGeometry(innerWidth, unit.shutter.drop, 0.1),
      cache.plain(`shutter:${plan.eraId}:${unit.shutter.kind}`, unit.shutter.colour, {
        roughness: 0.5,
        metalness: 0.5,
      }),
    )
    shutter.position.set(0, unit.glazing.headHeight - unit.shutter.drop / 2, unit.frame.depth * 0.55)
    addMesh(group, shutter, `${unit.anchor}:shutter`, {
      kind: 'shutter',
      anchor: unit.anchor,
      eraId: plan.eraId,
      shutter: unit.shutter.kind,
    })
  }

  // Awning: a sloped canvas from the glazing head down to the street, with the
  // valance hanging vertically at its edge — the period silhouette of a shop.
  const slope = Math.hypot(unit.awning.projection, unit.awning.drop)
  const tilt = Math.atan2(unit.awning.drop, unit.awning.projection)
  const awningGeometry = new PlaneGeometry(unit.width * 0.98, slope, 1, 1)
  awningGeometry.rotateX(-Math.PI / 2)
  awningGeometry.rotateX(tilt)
  awningGeometry.translate(
    0,
    unit.glazing.headHeight - unit.awning.drop / 2,
    unit.awning.projection / 2,
  )
  const awningMaterial = cache.sign(unit.awning.surface, true)
  addMesh(group, new Mesh(awningGeometry, awningMaterial), `${unit.anchor}:awning`, {
    kind: 'awning',
    anchor: unit.anchor,
    eraId: plan.eraId,
    awning: unit.awning.kind,
    emissive: unit.awning.surface.emissive,
    illumination: unit.awning.surface.illumination,
  })
  const valance = new Mesh(new PlaneGeometry(unit.width * 0.98, 0.26), awningMaterial)
  valance.position.set(
    0,
    unit.glazing.headHeight - unit.awning.drop - 0.13,
    unit.awning.projection,
  )
  addMesh(group, valance, `${unit.anchor}:awning-valance`, {
    kind: 'awning-valance',
    anchor: unit.anchor,
    eraId: plan.eraId,
    emissive: unit.awning.surface.emissive,
  })

  // Fascia board, mounted on the bay's own `parcel:<id>:sign:<n>` anchor.
  const boardLocal = toLocalPoint(unit.signBoard.position, unit.position, unit.rotationY)
  const signFrame = new Mesh(
    new BoxGeometry(unit.signBoard.width + 0.1, unit.signBoard.height + 0.1, 0.08),
    cache.plain(`sign-frame:${plan.eraId}`, unit.signBoard.frameColour, {
      roughness: 0.55,
      metalness: 0.3,
    }),
  )
  signFrame.position.set(boardLocal[0], boardLocal[1], boardLocal[2] - 0.03)
  addMesh(group, signFrame, `${unit.anchor}:sign-frame`, {
    kind: 'sign-frame',
    anchor: unit.anchor,
    eraId: plan.eraId,
  })
  const board = new Mesh(
    new BoxGeometry(unit.signBoard.width, unit.signBoard.height, 0.12),
    cache.sign(unit.signBoard.surface),
  )
  board.position.set(boardLocal[0], boardLocal[1], boardLocal[2] + 0.04)
  addMesh(group, board, `${unit.anchor}:sign`, {
    kind: 'sign',
    anchor: unit.anchor,
    eraId: plan.eraId,
    anchorName: unit.signBoard.anchor,
    shopType: unit.shopType,
    illumination: unit.signBoard.illumination,
    emissive: unit.signBoard.emissive,
    text: unit.signBoard.surface.lines.map((line) => line.text).join(' · '),
  })

  return group
}

function buildAdvertisingMesh(
  placement: AdvertisingPlacement,
  plan: StorefrontPlan,
  cache: StorefrontMaterialCache,
  index: number,
): Mesh {
  const mesh = new Mesh(
    new PlaneGeometry(placement.width, placement.height),
    cache.sign(placement.surface, true),
  )
  mesh.name = `ad:${placement.kind}:${placement.anchor}:${index}`
  mesh.position.set(placement.position.x, placement.position.y, placement.position.z)
  mesh.rotation.y = placement.rotationY
  mesh.userData = {
    kind: placement.kind,
    anchor: placement.anchor,
    eraId: plan.eraId,
    mount: placement.mount,
    campaign: placement.copy.tag,
    brand: placement.copy.brand,
    headline: placement.copy.headline,
    illumination: placement.illumination,
    emissive: placement.emissive,
  }
  return mesh
}

function buildGraffitiMesh(
  mark: GraffitiPlacement,
  plan: StorefrontPlan,
  cache: StorefrontMaterialCache,
  index: number,
): Mesh {
  const mesh = new Mesh(
    new PlaneGeometry(mark.width, mark.height),
    cache.graffiti(mark.surface, mark.opacity),
  )
  mesh.name = `graffiti:${mark.style}:${mark.anchor}:${index}`
  mesh.position.set(mark.position.x, mark.position.y, mark.position.z)
  mesh.rotation.y = mark.rotationY
  mesh.renderOrder = 2
  mesh.userData = {
    kind: 'graffiti',
    anchor: mark.anchor,
    eraId: plan.eraId,
    state: mark.state,
    style: mark.style,
    text: mark.text,
    colour: mark.colour,
    opacity: mark.opacity,
  }
  return mesh
}

/**
 * Builds the era's whole layer as one named group.
 *
 * Children are ordered deterministically — every bay in anchor order, then the
 * advertising placements, then the graffiti — which is what makes
 * {@link applyProgressiveSwap} a stable, repeatable staged reveal.
 */
export function createStorefrontGroup(
  plan: StorefrontPlan,
  options: StorefrontGroupOptions = {},
): Group {
  const factory = options.canvasFactory ?? createDefaultSignCanvasFactory()
  const cache = new StorefrontMaterialCache(factory, plan.lighting.artificialLightColor)
  const group = new Group()
  group.name = `storefronts:${plan.eraId}`
  group.userData = {
    kind: 'layer',
    eraId: plan.eraId,
    year: plan.year,
    night: plan.night,
    qualityTier: plan.qualityTier,
    textureBudgetBytes: plan.stats.textureBudgetBytes,
  }
  void options.interiors

  for (const unit of plan.units) {
    group.add(buildUnitGroup(unit, plan, cache))
  }
  plan.advertising.forEach((placement, index) => {
    group.add(buildAdvertisingMesh(placement, plan, cache, index))
  })
  plan.graffiti.forEach((mark, index) => {
    group.add(buildGraffitiMesh(mark, plan, cache, index))
  })
  // The cache dies with the group; materials are shared between its meshes.
  group.userData['textureCount'] = cache.textureCount
  return group
}

/** Disposes every geometry, material and texture under a storefront group. */
export function disposeStorefrontGroup(group: Group): void {
  const materials = new Set<Material>()
  const textures = new Set<Texture>()
  group.traverse((object) => {
    if (!(object instanceof Mesh)) {
      return
    }
    object.geometry.dispose()
    const list = Array.isArray(object.material) ? object.material : [object.material]
    for (const material of list) {
      materials.add(material)
      const map = (material as MeshStandardMaterial).map
      if (map !== null && map !== undefined) {
        textures.add(map)
      }
    }
  })
  for (const texture of textures) {
    texture.dispose()
  }
  for (const material of materials) {
    material.dispose()
  }
}

/**
 * Progressive staged reveal.
 *
 * `mix` 0 shows the outgoing era's block, `mix` 1 the incoming one; in between
 * the two groups are revealed shop by shop, sign by sign, so a staged change
 * reads as the block being converted rather than as a cut. Reduced motion never
 * gets here: {@link applyEraTransition} snaps `mix` to 0 or 1 first.
 *
 * Returns how many children were switched, which the browser harness reports.
 */
export function applyProgressiveSwap(from: Group, to: Group, mix: number): number {
  const clamped = Math.min(1, Math.max(0, mix))
  // Each era's block has a different number of objects, so the reveal is a
  // fraction of each group: at `mix` the incoming block shows its first
  // fraction and the outgoing block keeps the rest.
  const switched = Math.round(clamped * to.children.length)
  const retired = Math.round(clamped * from.children.length)
  to.children.forEach((child, index) => {
    child.visible = index < switched
  })
  from.children.forEach((child, index) => {
    child.visible = index >= retired
  })
  return switched
}

/* ------------------------------------------------------------------------- *
 * Scene summary
 * ------------------------------------------------------------------------- */

/** Counts and emissive state read back off a mounted storefront group. */
export interface StorefrontSceneSummary {
  readonly eraId: string
  readonly year: number
  readonly night: boolean
  readonly objects: number
  readonly meshes: number
  readonly byKind: Readonly<Record<string, number>>
  readonly unitGroups: number
  readonly signMeshes: number
  readonly awningMeshes: number
  readonly advertisingMeshes: number
  readonly graffitiMeshes: number
  readonly litMeshes: number
  readonly meanEmissiveIntensity: number
  readonly maxEmissiveIntensity: number
  readonly emissiveColour: string
  /** Colour the fascia boards glow with, read off the sign meshes. */
  readonly emissiveSignColour: string
  readonly signSignText: readonly string[]
  readonly emissiveSigns: number
  readonly textureCount: number
}

/**
 * Reads the mounted layer back: how many of each object kind exist, how many
 * carry lit material, and how strongly. The browser suite asserts era-correct
 * illumination from exactly these numbers.
 */
export function summariseStorefrontGroup(group: Group): StorefrontSceneSummary {
  const byKind: Record<string, number> = {}
  const signSignText: string[] = []
  let objects = 0
  let meshes = 0
  let unitGroups = 0
  let signMeshes = 0
  let awningMeshes = 0
  let advertisingMeshes = 0
  let graffitiMeshes = 0
  let litMeshes = 0
  let emissiveSigns = 0
  let emissiveTotal = 0
  let maxEmissive = 0
  let emissiveColour = '#000000'
  let signEmissive = 0
  let emissiveSignColour = '#000000'

  group.traverse((object) => {
    objects += 1
    const kind = typeof object.userData['kind'] === 'string' ? (object.userData['kind'] as string) : 'other'
    if (object instanceof Group && kind === 'unit') {
      unitGroups += 1
    }
    if (!(object instanceof Mesh)) {
      return
    }
    meshes += 1
    byKind[kind] = (byKind[kind] ?? 0) + 1
    if (kind === 'sign') {
      signMeshes += 1
      const text = object.userData['text']
      if (typeof text === 'string') {
        signSignText.push(text)
      }
    }
    if (kind === 'awning' || kind === 'awning-valance') {
      awningMeshes += 1
    }
    if (kind === 'billboard' || kind === 'painted-wall' || kind === 'poster-panel' || kind === 'newspaper-board' || kind === 'transient') {
      advertisingMeshes += 1
    }
    if (kind === 'graffiti') {
      graffitiMeshes += 1
    }
    const material = object.material as MeshStandardMaterial
    const intensity = typeof material.emissiveIntensity === 'number' ? material.emissiveIntensity : 0
    // "Lit" is a property of the object, not just of a number: a sign is lit
    // when the period gave it self-luminous hardware, and shop glazing is lit
    // while the block is dark. three.js defaults `emissiveIntensity` to 1 even
    // when nothing glows, so a non-black emissive colour is required too.
    const illumination = object.userData['illumination']
    const selfLuminous =
      isIlluminationKind(illumination) && isIlluminated(illumination)
    const glows =
      material.emissive instanceof Color &&
      material.emissive.getHex() !== 0 &&
      intensity > 0 &&
      (selfLuminous || kind === 'glazing' || kind === 'door-glazing')
    if (glows) {
      litMeshes += 1
      if (kind === 'sign' && selfLuminous) {
        emissiveSigns += 1
      }
      if (kind === 'sign' && intensity > signEmissive) {
        signEmissive = intensity
        emissiveSignColour = `#${material.emissive.getHexString()}`
      }
      emissiveTotal += intensity
      if (intensity > maxEmissive) {
        maxEmissive = intensity
        emissiveColour = `#${material.emissive.getHexString()}`
      }
    }
  })

  return {
    eraId: typeof group.userData['eraId'] === 'string' ? (group.userData['eraId'] as string) : 'unknown',
    year: typeof group.userData['year'] === 'number' ? (group.userData['year'] as number) : 0,
    night: group.userData['night'] === true,
    objects,
    meshes,
    byKind,
    unitGroups,
    signMeshes,
    awningMeshes,
    advertisingMeshes,
    graffitiMeshes,
    litMeshes,
    meanEmissiveIntensity: meshes === 0 ? 0 : Number((emissiveTotal / meshes).toFixed(4)),
    maxEmissiveIntensity: Number(maxEmissive.toFixed(4)),
    emissiveColour,
    emissiveSignColour,
    signSignText,
    emissiveSigns,
    textureCount: typeof group.userData['textureCount'] === 'number' ? (group.userData['textureCount'] as number) : 0,
  }
}

/* ------------------------------------------------------------------------- *
 * React host
 * ------------------------------------------------------------------------- */

/** Props of the React layer the scene integration mounts. */
export interface StorefrontsLayerProps {
  /** Era to dress the block for. */
  readonly eraId: EraId
  /** The real block: anchors are read, never created or moved. */
  readonly layout: BlockLayout
  readonly qualityTier?: QualityTierName
  /** Overrides the night flag derived from the era's lighting. */
  readonly night?: boolean
  readonly seed?: Seed
  readonly reducedMotion?: boolean
  /** Staged change; the layer then cross-fades `from` → `to`. */
  readonly transition?: StorefrontTransition | null
  /** Injectable artwork factory (tests and the harness substitute their own). */
  readonly canvasFactory?: AnySignCanvasFactory
  readonly visible?: boolean
  /** Called whenever a new plan is built, for instrumentation and harnesses. */
  readonly onPlan?: (plan: StorefrontPlan) => void
}

interface LayerGroups {
  readonly single: Group | null
  readonly from: Group | null
  readonly to: Group | null
}

/**
 * React host for the storefront layer.
 *
 * The component is thin on purpose: it resolves the plan (one era, or a staged
 * pair), builds the three.js groups imperatively — the same builder the demo
 * harness and the imperative path use — and hands them to react-three-fiber as
 * primitives. A staged change mounts both groups and reveals them progressively.
 */
export function StorefrontsLayer(props: StorefrontsLayerProps): ReactElement {
  const {
    eraId,
    layout,
    qualityTier,
    night,
    seed,
    reducedMotion = false,
    transition = null,
    canvasFactory,
    visible = true,
    onPlan,
  } = props

  const factory = useMemo<AnySignCanvasFactory>(
    () => canvasFactory ?? createDefaultSignCanvasFactory(),
    [canvasFactory],
  )
  const context = useMemo<StorefrontContext>(
    () => ({ layout, seed, qualityTier, night, reducedMotion }),
    [layout, seed, qualityTier, night, reducedMotion],
  )
  const transitionKey = transition === null ? null : `${transition.from}:${transition.to}:${transition.t}`

  const staged = useMemo(
    () => (transition === null ? null : applyEraTransition(transition, context)),
    // The key covers every field of the transition; `transition` itself is
    // replaced on each frame by the director, so keying off its identity would
    // rebuild the plan on every render.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [transitionKey, context],
  )
  const plan = useMemo(
    () => (staged === null ? applyEra(eraId, context) : staged.plan),
    [staged, eraId, context],
  )

  const groups = useMemo<LayerGroups>(() => {
    const options: StorefrontGroupOptions = { canvasFactory: factory }
    if (staged !== null && !staged.instant && staged.from !== staged.to) {
      return {
        single: null,
        from: createStorefrontGroup(staged.fromPlan, options),
        to: createStorefrontGroup(staged.toPlan, options),
      }
    }
    return { single: createStorefrontGroup(plan, options), from: null, to: null }
  }, [plan, staged, factory])

  useEffect(() => {
    if (groups.from !== null && groups.to !== null) {
      applyProgressiveSwap(groups.from, groups.to, staged?.mix ?? 0)
    }
  }, [groups, staged])

  useEffect(() => {
    onPlan?.(plan)
  }, [plan, onPlan])

  useEffect(
    () => () => {
      if (groups.single !== null) {
        disposeStorefrontGroup(groups.single)
      }
      if (groups.from !== null) {
        disposeStorefrontGroup(groups.from)
      }
      if (groups.to !== null) {
        disposeStorefrontGroup(groups.to)
      }
    },
    [groups],
  )

  return (
    <>
      {groups.single !== null ? (
        <primitive object={groups.single} visible={visible} />
      ) : null}
      {groups.from !== null ? (
        <primitive object={groups.from} visible={visible} />
      ) : null}
      {groups.to !== null ? (
        <primitive object={groups.to} visible={visible} />
      ) : null}
    </>
  )
}

/** Name the plan's own brief uses for the layer; identical to the React host. */
export const StorefrontLayer = StorefrontsLayer

/** Re-exported so the barrel stays the single import path for the scene. */
export type StorefrontLayerProps = StorefrontsLayerProps
