/*
 * Mario (small form) 16x16 frames — idle / walk1-3 / jump / skid / death / flagSlide.
 *
 * Palette string-map pixel art authored as data (no image assets).
 * '.' is transparent; every other character maps to a hex color in
 * `palette`. Rendered exclusively with Canvas 2D fillRect by
 * src/render/pixelArt.js drawPixels() — see the renderer for the frame
 * contract ({ palette, width, height, rows }).
 *
 * Original approximation art in the classic style; no ripped sprites.
 */
export const marioSmall = {
  'idle': {
    palette: { 'r': '#d92a1a', 's': '#f8b07a', 'b': '#2456e0', 'h': '#6e3a1c', 'o': '#8a4a22', 'k': '#262626', 'w': '#f8f8f8', 'y': '#f8d040' },
    width: 16,
    height: 16,
    rows: [
        '................',
        '........k.......',
        '.......kkkk.....',
        '......krrrkk....',
        '.....krrrrrsk...',
        '.....krssssrk...',
        '.....kswsssk....',
        '.....ksssssrk...',
        '.....ksssssrk...',
        '.....kssssrk....',
        '.....kbbbbbk....',
        '....kbbbbbbbk...',
        '....kbbybbybk...',
        '....kbbbbbbbk...',
        '...kkbbbbbbk....',
        '...kkobbbbok....'
    ],
  },
  'walk1': {
    palette: { 'r': '#d92a1a', 's': '#f8b07a', 'b': '#2456e0', 'h': '#6e3a1c', 'o': '#8a4a22', 'k': '#262626', 'w': '#f8f8f8', 'y': '#f8d040' },
    width: 16,
    height: 16,
    rows: [
        '................',
        '........k.......',
        '.......kkkk.....',
        '......krrrkk....',
        '.....krrrrrsk...',
        '.....krssssrk...',
        '.....kswsssk....',
        '.....ksssssrk...',
        '.....ksssssrk...',
        '.....kssssrk....',
        '.....kbbbbbk....',
        '....kbbbbbbbk...',
        '....kbbybbybk...',
        '....kbbbbbbbk...',
        '...kkbbbbbbk....',
        '...kkobbbbok....'
    ],
  },
  'walk2': {
    palette: { 'r': '#d92a1a', 's': '#f8b07a', 'b': '#2456e0', 'h': '#6e3a1c', 'o': '#8a4a22', 'k': '#262626', 'w': '#f8f8f8', 'y': '#f8d040' },
    width: 16,
    height: 16,
    rows: [
        '................',
        '........k.......',
        '.......kkkk.....',
        '......krrrkk....',
        '.....krrrrrsk...',
        '.....krssssrk...',
        '.....kswsssk....',
        '.....ksssssrk...',
        '.....ksssssrk...',
        '.....kssssrk....',
        '.....kbbbbbk....',
        '....kbbbbbbbk...',
        '....kbbybbybk...',
        '....kbbbbbbbk...',
        '.....kbbbbbk....',
        '....kkobbokk....'
    ],
  },
  'walk3': {
    palette: { 'r': '#d92a1a', 's': '#f8b07a', 'b': '#2456e0', 'h': '#6e3a1c', 'o': '#8a4a22', 'k': '#262626', 'w': '#f8f8f8', 'y': '#f8d040' },
    width: 16,
    height: 16,
    rows: [
        '................',
        '........k.......',
        '.......kkkk.....',
        '......krrrkk....',
        '.....krrrrrsk...',
        '.....krssssrk...',
        '.....kswsssk....',
        '.....ksssssrk...',
        '.....ksssssrk...',
        '.....kssssrk....',
        '.....kbbbbbk....',
        '....kbbbbbbbk...',
        '....kbbybbybk...',
        '....kbbbbbbbk...',
        '....kkbbbbbkk...',
        '........kkkk....'
    ],
  },
  'jump': {
    palette: { 'r': '#d92a1a', 's': '#f8b07a', 'b': '#2456e0', 'h': '#6e3a1c', 'o': '#8a4a22', 'k': '#262626', 'w': '#f8f8f8', 'y': '#f8d040' },
    width: 16,
    height: 16,
    rows: [
        '................',
        '........k.......',
        '.......kkkk.....',
        '......krrrkk....',
        '.....krrrrrsk...',
        '.....krssssrk...',
        '.....kswsssk....',
        '.....ksssssrk...',
        '.....kssssrk....',
        '...k..ksssrk....',
        '...k.kbbbbbk....',
        '...kkbbbbbbbk...',
        '....kbybbybk....',
        '....kbbbbbbk....',
        '...kkbbbbbbkk...',
        '...kobbbbbbbok..'
    ],
  },
  'skid': {
    palette: { 'r': '#d92a1a', 's': '#f8b07a', 'b': '#2456e0', 'h': '#6e3a1c', 'o': '#8a4a22', 'k': '#262626', 'w': '#f8f8f8', 'y': '#f8d040' },
    width: 16,
    height: 16,
    rows: [
        '................',
        '........k.......',
        '.......kkkk.....',
        '......krrrkk....',
        '.....krrrrrsk...',
        '.....krssssrk...',
        '.....kswsssk....',
        '.....ksssssrk...',
        '.....ksssssrk...',
        '.....kssssrk....',
        '.....kbbbbbbk...',
        '....kbbbbbbbk...',
        '....kbbybbybk...',
        '...kbbbbbbbbk...',
        '...kbbbbbbbk....',
        '..kobbbbbbbk....'
    ],
  },
  'death': {
    palette: { 'r': '#d92a1a', 's': '#f8b07a', 'b': '#2456e0', 'h': '#6e3a1c', 'o': '#8a4a22', 'k': '#262626', 'w': '#f8f8f8', 'y': '#f8d040' },
    width: 16,
    height: 16,
    rows: [
        '................',
        '......kkk.......',
        '....kkrrrkk.....',
        '...krsssssrk....',
        '...ksswsssrk....',
        '...kssssssrk....',
        '..k.ssssssrk....',
        '..k.ssssssrk....',
        '..kksssssrk.....',
        '..krssssssrk....',
        '..krrrrrrrk.....',
        '..kbbbbbbbk.....',
        '.kbbbybbybbk....',
        '.kkbbbbbbbbk....',
        '..kkbbbbbbkk....',
        '..kkbbbbbbkk....'
    ],
  },
  'flagSlide': {
    palette: { 'r': '#d92a1a', 's': '#f8b07a', 'b': '#2456e0', 'h': '#6e3a1c', 'o': '#8a4a22', 'k': '#262626', 'w': '#f8f8f8', 'y': '#f8d040' },
    width: 16,
    height: 16,
    rows: [
        '................',
        '..ss............',
        '..ss............',
        '..ss............',
        '...rrrrr........',
        '...rrrrrr.......',
        '...rssssr.......',
        '...rswssr.......',
        '...rssssr.......',
        '...rssss........',
        '....bbbbb.......',
        '....bbbbb.......',
        '....byybb.......',
        '....bbbbb.......',
        '....bbbbb.......',
        '...kobbbk.......'
    ],
  },
};
