/*
 * Mario (super form after a mushroom) 16x32 frames — idle / walk1-3 / jump / skid / flagSlide.
 *
 * Palette string-map pixel art authored as data (no image assets).
 * '.' is transparent; every other character maps to a hex color in
 * `palette`. Rendered exclusively with Canvas 2D fillRect by
 * src/render/pixelArt.js drawPixels() — see the renderer for the frame
 * contract ({ palette, width, height, rows }).
 *
 * Original approximation art in the classic style; no ripped sprites.
 */
export const marioSuper = {
  'idle': {
    palette: { 'r': '#d92a1a', 's': '#f8b07a', 'b': '#2456e0', 'h': '#6e3a1c', 'o': '#8a4a22', 'k': '#262626', 'w': '#f8f8f8', 'y': '#f8d040' },
    width: 16,
    height: 32,
    rows: [
        '................',
        '................',
        '................',
        '........k.......',
        '.......kkkk.....',
        '......krrrkk....',
        '.....krrrrrsk...',
        '.....krssssrk...',
        '.....kswsssk....',
        '.....ksssssrk...',
        '.....ksssssrk...',
        '.....kssssrk....',
        '.....krrrrrk....',
        '....krrrrrrrk...',
        '....kbbrrrrbk...',
        '....kbbbbybbk...',
        '....kbbbbbbyk...',
        '...kbbbbbbbbk...',
        '...kbbbbbybbk...',
        '...kbbbbybbbk...',
        '...kbbbbbbbbk...',
        '...kbbbbbbbbk...',
        '..kbbbbbbbbbbk..',
        '..kbbbbbbbbbbk..',
        '..kbbbbbbbbbbk..',
        '...kbbbbbbbbk...',
        '...kbbbbbbbbk...',
        '...kbbbbbbbbk...',
        '..kkbbbbbbbbkk..',
        '..kkbbbbbbbbkk..',
        '..kkobbbbbbbokk.',
        '...kobbbbbbbok..'
    ],
  },
  'walk1': {
    palette: { 'r': '#d92a1a', 's': '#f8b07a', 'b': '#2456e0', 'h': '#6e3a1c', 'o': '#8a4a22', 'k': '#262626', 'w': '#f8f8f8', 'y': '#f8d040' },
    width: 16,
    height: 32,
    rows: [
        '................',
        '................',
        '................',
        '........k.......',
        '.......kkkk.....',
        '......krrrkk....',
        '.....krrrrrsk...',
        '.....krssssrk...',
        '.....kswsssk....',
        '.....ksssssrk...',
        '.....ksssssrk...',
        '.....kssssrk....',
        '.....krrrrrk....',
        '....krrrrrrrk...',
        '....kbbrrrrbk...',
        '....kbbbbybbk...',
        '....kbbbbbbyk...',
        '...kbbbbbbbbk...',
        '...kbbbbbybbk...',
        '...kbbbbybbbk...',
        '...kbbbbbbbbk...',
        '...kbbbbbbbbk...',
        '..kbbbbbbbbbbk..',
        '..kbbbbbbbbbbk..',
        '..kbbbbbbbbbbk..',
        '...kbbbbbbbbk...',
        '...kbbbbbbbbk...',
        '....kbbbbbbk....',
        '....kkbbbbkk....',
        '...kbbbbbbbbk...',
        '..kobbbbbbbbkk..',
        '...kobbbbbbbok..'
    ],
  },
  'walk2': {
    palette: { 'r': '#d92a1a', 's': '#f8b07a', 'b': '#2456e0', 'h': '#6e3a1c', 'o': '#8a4a22', 'k': '#262626', 'w': '#f8f8f8', 'y': '#f8d040' },
    width: 16,
    height: 32,
    rows: [
        '................',
        '................',
        '................',
        '........k.......',
        '.......kkkk.....',
        '......krrrkk....',
        '.....krrrrrsk...',
        '.....krssssrk...',
        '.....kswsssk....',
        '.....ksssssrk...',
        '.....ksssssrk...',
        '.....kssssrk....',
        '.....krrrrrk....',
        '....krrrrrrrk...',
        '....kbbrrrrbk...',
        '....kbbbbybbk...',
        '....kbbbbbbyk...',
        '...kbbbbbbbbk...',
        '...kbbbbbybbk...',
        '...kbbbbybbbk...',
        '...kbbbbbbbbk...',
        '...kbbbbbbbbk...',
        '..kbbbbbbbbbbk..',
        '..kbbbbbbbbbbk..',
        '..kbbbbbbbbbbk..',
        '...kbbbbbbbbk...',
        '...kbbbbbbbbk...',
        '...kbbbbbbbbk...',
        '..kkbbbbbbbbkk..',
        '..kkbbbbbbbbkk..',
        '...kkbbbbbbkk...',
        '...kkobbbbkok...'
    ],
  },
  'walk3': {
    palette: { 'r': '#d92a1a', 's': '#f8b07a', 'b': '#2456e0', 'h': '#6e3a1c', 'o': '#8a4a22', 'k': '#262626', 'w': '#f8f8f8', 'y': '#f8d040' },
    width: 16,
    height: 32,
    rows: [
        '................',
        '................',
        '................',
        '........k.......',
        '.......kkkk.....',
        '......krrrkk....',
        '.....krrrrrsk...',
        '.....krssssrk...',
        '.....kswsssk....',
        '.....ksssssrk...',
        '.....ksssssrk...',
        '.....kssssrk....',
        '.....krrrrrk....',
        '....krrrrrrrk...',
        '....kbbrrrrbk...',
        '....kbbbbybbk...',
        '....kbbbbbbyk...',
        '...kbbbbbbbbk...',
        '...kbbbbbybbk...',
        '...kbbbbybbbk...',
        '...kbbbbbbbbk...',
        '...kbbbbbbbbk...',
        '..kbbbbbbbbbbk..',
        '..kbbbbbbbbbbk..',
        '..kbbbbbbbbbbk..',
        '...kbbbbbbbbk...',
        '...kbbbbbbbbk...',
        '...kbbbbbbbbk...',
        '....kbbbbbbbk...',
        '....kkbbbbbbk...',
        '.....kkbbbbkk...',
        '...kkobbbbbok...'
    ],
  },
  'jump': {
    palette: { 'r': '#d92a1a', 's': '#f8b07a', 'b': '#2456e0', 'h': '#6e3a1c', 'o': '#8a4a22', 'k': '#262626', 'w': '#f8f8f8', 'y': '#f8d040' },
    width: 16,
    height: 32,
    rows: [
        '................',
        '................',
        '......k.........',
        '.....kkkk.......',
        '....kkrrrkk.....',
        '...krrrrrskk....',
        '...krsssssrk....',
        '...kswwwssrk....',
        '...kssssssrk....',
        '...ksssssssk....',
        '...kssssssrk....',
        '...ksssssrk.....',
        '...krrrrrk......',
        '..krrrrrrrk.....',
        '..kbbbrrrrk.....',
        '..kbbbbybbk.....',
        '..kbbbbbbyk.....',
        '.kbbbbbbbbk.....',
        '.kbbbbbybbk.....',
        '.kbbbbybbbk.....',
        '.kbbbbbbbbk.....',
        '..kbbbbbbbbk....',
        '..kbbbbbbbbk....',
        '...kbbbbbbbk....',
        '...kkbbbbbkk....',
        '...kkbbbbbkk....',
        '...kkbbbbbkk....',
        '..kkbbbbbbbkk...',
        '..kbbbbbbbbbk...',
        '..kbbbbbbbbbk...',
        '..kobbbbbbbbkok.',
        '...kkkkkkkkkk...'
    ],
  },
  'skid': {
    palette: { 'r': '#d92a1a', 's': '#f8b07a', 'b': '#2456e0', 'h': '#6e3a1c', 'o': '#8a4a22', 'k': '#262626', 'w': '#f8f8f8', 'y': '#f8d040' },
    width: 16,
    height: 32,
    rows: [
        '................',
        '................',
        '................',
        '........k.......',
        '.......kkkk.....',
        '......krrrkk....',
        '.....krrrrrsk...',
        '.....krssssrk...',
        '.....kswsssk....',
        '.....ksssssrk...',
        '.....ksssssrk...',
        '.....kssssrk....',
        '....krrrrrrk....',
        '....krrrrrrrk...',
        '...kbrrrrrrbk...',
        '...kbbbybbbk....',
        '...kbbbbbybk....',
        '..kbbbbbbbbk....',
        '..kbbbbbybbk....',
        '..kbbbbybbbk....',
        '..kbbbbbbbbk....',
        '..kbbbbbbbbk....',
        '.kbbbbbbbbbbk...',
        '.kbbbbbbbbbbk...',
        '.kbbbbbbbbbbk...',
        '..kbbbbbbbbk....',
        '..kbbbbbbbbk....',
        '..kbbbbbbbbk....',
        '..kkbbbbbbkk....',
        '..kkbbbbbbkk....',
        '...kbbbbbbk.....',
        '...kkobbbbkok...'
    ],
  },
  'flagSlide': {
    palette: { 'r': '#d92a1a', 's': '#f8b07a', 'b': '#2456e0', 'h': '#6e3a1c', 'o': '#8a4a22', 'k': '#262626', 'w': '#f8f8f8', 'y': '#f8d040' },
    width: 16,
    height: 32,
    rows: [
        '................',
        '..ss............',
        '..ss............',
        '..ss............',
        '..ss............',
        '...rrrrr........',
        '...rrrrrr.......',
        '...rssssr.......',
        '...rswssr.......',
        '...rssssr.......',
        '...rssssr.......',
        '...rssss........',
        '....bbbbb.......',
        '....bbbbb.......',
        '....bbbbb.......',
        '....bbbbb.......',
        '....bbbbb.......',
        '....byybb.......',
        '....bbbbb.......',
        '....bbbbb.......',
        '....bbbbb.......',
        '....bbbbb.......',
        '...bbbbbbb......',
        '...bbbbbbb......',
        '...bbbbbbb......',
        '...bbbbbbb......',
        '...bbbbbbb......',
        '...bbbbbbb......',
        '...bbbbbbb......',
        '...bb.bbb.......',
        '...kobbbb.......',
        '...kobbbb.......'
    ],
  },
};
