/*
 * Tile frames — ground, brick, usedBlock, question1-3 (shimmer),
 * pipeTopLeft/Right, pipeBodyLeft/Right, flagpole, flag and the 80x80 castle.
 *
 * Palette string-map pixel art authored as data (no image assets).
 * '.' is transparent; every other character maps to a hex color in
 * `palette`. Rendered exclusively with Canvas 2D fillRect by
 * src/render/pixelArt.js drawPixels() — see the renderer for the frame
 * contract ({ palette, width, height, rows }).
 *
 * Original approximation art in the classic style; no ripped sprites.
 */
export const tiles = {
  'ground': {
    palette: { 'b': '#b04a1e', 'd': '#7a2e10', 'l': '#d8763a', 's': '#5c2a0c' },
    width: 16,
    height: 16,
    rows: [
        'bbbbbbbbbbbbbbbb',
        'bbbbbbbbbbbbbbbb',
        'bblbbbbbbbbbbbbb',
        'bbbbbdbbbbbbbbbb',
        'bbbbbbbbbbbbbbbb',
        'bbbbbbbblbbbbbbb',
        'bbbbbbbbbbbbdbbb',
        'bbbbbbbbbbbbbbbb',
        'blbbbbbbbbbbbbbb',
        'bbbbbbbbdbbbbbbb',
        'bbbbbbbbbbbbbbbb',
        'bbbbbdbbbbbbbbbb',
        'bbbbbbbbbbbbblbb',
        'bbbbbbbbbbbbbbbb',
        'ssssssssssssssss',
        'ssssssssssssssss'
    ],
  },
  'brick': {
    palette: { 'b': '#c04a28', 'm': '#6e2a14', 'l': '#e88440', 's': '#8a3418' },
    width: 16,
    height: 16,
    rows: [
        'llbbbbbbbbbbbbbb',
        'bbbbbbbbbbbbbbbb',
        'bbbbbbbbbbbbbbss',
        'bbbbbbbbbbbbbbbb',
        'bbbbbbbbbbbbbbbb',
        'bbbbbbbbbbbbbbbb',
        'mmmmmmmmmmmmmmmm',
        'bbbbbbbbbbbbbbss',
        'llbbbbbbssbbbbbb',
        'bbbbbbbbbbbbbbbb',
        'bbbbbbbbbbbbbbbb',
        'bbbbbbbbbbbbbbbb',
        'ssbbbbbbbbbbbbbb',
        'bbbbbbbbbbbbbbbb',
        'mmmmmmmmmmmmmmmm',
        'bbbbbbbbbbllbbbb'
    ],
  },
  'usedBlock': {
    palette: { 'b': '#8a5a2a', 'd': '#5a3418', 'l': '#b88240', 'k': '#3a2010' },
    width: 16,
    height: 16,
    rows: [
        'kkkkkkkkkkkkkkkk',
        'kllbbbbbbbbbbbbk',
        'kbbbbbbbbbbbbbdb',
        'kbbddbbbbbbbddbk',
        'kbbbbbbbbbbbbbbk',
        'kdbbbbbbbbbbbbbk',
        'kbbbbbbbbbbbdbbk',
        'kbdbbbbbbbbbbbbk',
        'kbbbbbbbbbbbbbdk',
        'kbbbbbdbbbbbbbbk',
        'kbbbbbbbbbbbbbdb',
        'kbbbbbbbbbbbbbbk',
        'kbddbbbbbbbbbdbk',
        'kbbbbbbbbbbbbbbk',
        'kbbbbbbbbbbbbbbk',
        'kkkkkkkkkkkkkkkk'
    ],
  },
  'question1': {
    palette: { 'y': '#e8b038', 'o': '#a86818', 'd': '#c88818', 'h': '#f8e080', 'w': '#f8f8f8' },
    width: 16,
    height: 16,
    rows: [
        'oooooooooooooooo',
        'ohhyyyyyyyyyyyyo',
        'oyywwwwwwwwywyyo',
        'oyywwwyywwwyyyyo',
        'oyywwwyywwwyyyyo',
        'oyyywwyywwwyyyyo',
        'oyyywwyywwwyyyyo',
        'oyyyywyywwwyyyyo',
        'oyyyyyyywwwyyyyo',
        'oyyyyyyywwwyyyyo',
        'oyyyyyyywwwyyyyo',
        'oyyyyyyywwwyyyyo',
        'oywyyyyywwwyyyyo',
        'oyyyyyywwwyyyyyo',
        'oyyyyyyyyyyyyyyo',
        'oooooooooooooooo'
    ],
  },
  'question2': {
    palette: { 'y': '#e8b038', 'o': '#a86818', 'd': '#c88818', 'h': '#f8e080', 'w': '#f8f8f8' },
    width: 16,
    height: 16,
    rows: [
        'oooooooooooooooo',
        'ohhyyyyyyyyyyyyo',
        'oyywwwwwwwwyyyyo',
        'oyywwwyywwwyywyo',
        'oyywwwyywwwyyyyo',
        'oyyywwyywwwyyyyo',
        'oyyywwyywwwyyyyo',
        'oyyyywyywwwyyyyo',
        'oyyyyyyywwwyyyyo',
        'oyyyyyyywwwyyyyo',
        'oyyyyyyywwwyyyyo',
        'oyyyyyyywwwyyyyo',
        'oyyyyyyywwwyyyyo',
        'oywyyyywwwyyyyyo',
        'oyyyyyyyyyyyyyyo',
        'oooooooooooooooo'
    ],
  },
  'question3': {
    palette: { 'y': '#e8b038', 'o': '#a86818', 'd': '#c88818', 'h': '#f8e080', 'w': '#f8f8f8' },
    width: 16,
    height: 16,
    rows: [
        'oooooooooooooooo',
        'ohhyyyyyyyyyyyyo',
        'oyywwwwwwwwyywyo',
        'oyywwwyywwwyyyyo',
        'oyywwwyywwwyyyyo',
        'oyyywwyywwwyyyyo',
        'oyyywwyywwwyyyyo',
        'oyyyywyywwwyyyyo',
        'oyyyyyyywwwyyyyo',
        'oyyyyyyywwwyyyyo',
        'oyyyyyyywwwyyyyo',
        'oyywyyyywwwyyyyo',
        'oyyyyyyywwwyyyyo',
        'oyyyyyywwwyyyyyo',
        'oyyyyyyyyyyyyyyo',
        'oooooooooooooooo'
    ],
  },
  'pipeTopLeft': {
    palette: { 'a': '#5ce05c', 'b': '#3cc04c', 'c': '#209438', 'd': '#105c20' },
    width: 16,
    height: 16,
    rows: [
        '..aaaaaaaaaaaaa.',
        '..aaaaaaaaaaaaaa',
        '..abbbbbbbbbbbbd',
        '..abbbbbbbbbbbbd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd'
    ],
  },
  'pipeTopRight': {
    palette: { 'a': '#5ce05c', 'b': '#3cc04c', 'c': '#209438', 'd': '#105c20' },
    width: 16,
    height: 16,
    rows: [
        '.aaaaaaaaaaaaaa.',
        'aaaaaaaaaaaaaaa.',
        'dbbbbbbbbbbbbba.',
        'dbbbbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.'
    ],
  },
  'pipeBodyLeft': {
    palette: { 'a': '#5ce05c', 'b': '#3cc04c', 'c': '#209438', 'd': '#105c20' },
    width: 16,
    height: 16,
    rows: [
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd',
        '..abbbbbbbbbcccd'
    ],
  },
  'pipeBodyRight': {
    palette: { 'a': '#5ce05c', 'b': '#3cc04c', 'c': '#209438', 'd': '#105c20' },
    width: 16,
    height: 16,
    rows: [
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.',
        'dcccbbbbbbbbbba.'
    ],
  },
  'flagpole': {
    palette: { 'y': '#f8c828', 'Y': '#ffe878', 'k': '#3a3a3a', 'p': '#2f9e44', 'd': '#1e6e2c' },
    width: 16,
    height: 16,
    rows: [
        '................',
        '.......yy.......',
        '......kYYk......',
        '......kyyk......',
        '.......kk.......',
        '.......kpk......',
        '.......kpk......',
        '.......kpk......',
        '.......kpk......',
        '.......kpk......',
        '.......kpk......',
        '.......kpk......',
        '.......kpk......',
        '.......kpk......',
        '.......kpk......',
        '.......kpk......'
    ],
  },
  'flag': {
    palette: { 'g': '#2f9e44', 'w': '#f8f8f8', 'd': '#1e6e2c' },
    width: 16,
    height: 16,
    rows: [
        '................',
        '...gggg.........',
        '..gggggg........',
        '.gggggggg.......',
        '.ggwwggggg......',
        '.gggwwgggg......',
        '.ggggwwggg......',
        '.gggggwwgg......',
        '.ggggggwwg......',
        '.gggggggww......',
        '.dggggggdd......',
        '.dgggggdd.......',
        '.dggggdd........',
        '.dgggdd.........',
        '.dggdd..........',
        '.dddd...........'
    ],
  },
  'castle': {
    palette: { '#': '#565656', 'W': '#c9c9c9', 'w': '#a2a2a2', 'd': '#7e7e7e', 'k': '#3f2416', 'K': '#5e3820', 'g': '#e8c840' },
    width: 80,
    height: 80,
    rows: [
        '.WWWW....WWWW..................................................WWWW....WWWW.....',
        '.WWWW....WWWW..................................................WWWW....WWWW.....',
        '.##dddddddddddd##..............................................##dddddddddddd##.',
        '.##dddddddddddd##..............................................##dddddddddddd##.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#..............................................#wWWWWWWWWWWWWd#.',
        '.#wWWWWgggWWWWWd#..............................................#wWWWWgggWWWWWd#.',
        '.#wWWWWkkkWWWWWd#..............................................#wWWWWkkkWWWWWd#.',
        '.#wWWWWkkkWWWWWd#..............................................#wWWWWkkkWWWWWd#.',
        '.#wWWWWkkkWWWWWd#..............................................#wWWWWkkkWWWWWd#.',
        '.#wWWWWkkkWWWWWd#...WWW...WWW...WWW...WWW...WWW...WWW...WW.....#wWWWWkkkWWWWWd#.',
        '.#wWWWWkkkWWWWWd#...WWW...WWW...WWW...WWW...WWW...WWW...WW.....#wWWWWkkkWWWWWd#.',
        '.#wWWWWkkkWWWWWd#...########################################...#wWWWWkkkWWWWWd#.',
        '.#wWWWWkkkWWWWWd#...########################################...#wWWWWkkkWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWgggWWWWWWWWWWWWWWWWWgggWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWkkkWWWWWWWWWWWWWWWWWkkkWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWgggWWWWWWWWWWWWWWWWWgggWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWkkkWWWWWWWWWWWWWWWWWkkkWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#dddddddkkkdddddddddddddddddkkkdddddddd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWkkkWWWWWWWWWWWWWWWWWkkkWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWkkkWWWWWWWWWWWWWWWWWkkkWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#dddddddddddddddddddddddddddddddddddddd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWKkggggkKWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWK.kkkk.KWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWKkkkkkkKWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWKkkkkkkKWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWKkkkkkkKWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWKgkkkkgKWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#dddddddddddddddKkkkkkkKddddddddddddddd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWKkkkkkkKWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWKkkkkkkKWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWKkkkkkkKWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWKkkkkkkKWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWKkkkkkkKWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWKkkkkkkKWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWKgkkkkgKWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWKkkkkkkKWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWKKKKKKKKWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        '.#wWWWWWWWWWWWWd#...#wWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd#...#wWWWWWWWWWWWWd#.',
        'dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
        '################################################################################',
        'dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd'
    ],
  },
};
