export interface EraData {
  year: number;
  name: string;
  skyColor: [number, number, number];
  fogColor: [number, number, number];
  fogDensity: number;
  ambientIntensity: number;
  ambientColor: [number, number, number];
  sunIntensity: number;
  sunColor: [number, number, number];
  sunPosition: [number, number, number];
  groundColor: [number, number, number];
  roadColor: [number, number, number];
  buildingStyle: 'ww2' | 'midcentury' | 'neon' | 'digital' | 'modern' | 'futuristic';
  hasSnow: boolean;
  hasRain: boolean;
  hasFog: boolean;
  hasStars: boolean;
  starDensity: number;
  hasFlying: boolean;
  hasHolograms: boolean;
  hasElectricVehicles: boolean;
  hasClassicCars: boolean;
  hasMilitaryVehicles: boolean;
  hasModernSedan: boolean;
  hasNeonSigns: boolean;
  hasDigitalBillboards: boolean;
  hasHolographicAds: boolean;
  streetLampStyle: 'gas' | 'incandescent' | 'fluorescent' | 'led' | 'smart' | 'holographic';
  sidewalkStyle: 'dirt' | 'cobblestone' | 'concrete' | 'asphalt' | 'smart' | 'energy';
  pedestrianStyle: 'ww2' | '60s' | '80s' | '2000s' | 'modern' | 'futuristic';
  treeStyle: 'bare' | 'classic' | 'modern' | 'bio';
  fenceStyle: 'wooden' | 'iron' | 'steel' | 'energy';
  billboardAdStyle: 'handpainted' | 'neon' | 'digital' | 'holographic';
  particleType: 'none' | 'snow' | 'rain' | 'embers' | 'data' | 'aurora';
}

export const ERA_DATA: Record<number, EraData> = {
  1945: {
    year: 1945,
    name: 'Post-War Era',
    skyColor: [0.92, 0.88, 0.80],
    fogColor: [0.92, 0.88, 0.80],
    fogDensity: 0.012,
    ambientIntensity: 1.5,
    ambientColor: [0.85, 0.78, 0.65],
    sunIntensity: 3.0,
    sunColor: [1.0, 0.95, 0.8],
    sunPosition: [30, 25, 20],
    groundColor: [0.55, 0.50, 0.45],
    roadColor: [0.40, 0.37, 0.34],
    buildingStyle: 'ww2',
    hasSnow: false,
    hasRain: false,
    hasFog: true,
    hasStars: false,
    starDensity: 0,
    hasFlying: false,
    hasHolograms: false,
    hasElectricVehicles: false,
    hasClassicCars: false,
    hasMilitaryVehicles: true,
    hasModernSedan: false,
    hasNeonSigns: false,
    hasDigitalBillboards: false,
    hasHolographicAds: false,
    streetLampStyle: 'gas',
    sidewalkStyle: 'dirt',
    pedestrianStyle: 'ww2',
    treeStyle: 'bare',
    fenceStyle: 'wooden',
    billboardAdStyle: 'handpainted',
    particleType: 'none',
  },
  1965: {
    year: 1965,
    name: 'Mid-Century Modern',
    skyColor: [0.75, 0.88, 0.98],
    fogColor: [0.88, 0.90, 0.96],
    fogDensity: 0.006,
    ambientIntensity: 1.5,
    ambientColor: [0.75, 0.80, 0.90],
    sunIntensity: 3.0,
    sunColor: [1.0, 0.98, 0.85],
    sunPosition: [35, 30, 15],
    groundColor: [0.60, 0.65, 0.55],
    roadColor: [0.45, 0.45, 0.45],
    buildingStyle: 'midcentury',
    hasSnow: false,
    hasRain: false,
    hasFog: false,
    hasStars: false,
    starDensity: 0,
    hasFlying: false,
    hasHolograms: false,
    hasElectricVehicles: false,
    hasClassicCars: true,
    hasMilitaryVehicles: false,
    hasModernSedan: false,
    hasNeonSigns: false,
    hasDigitalBillboards: false,
    hasHolographicAds: false,
    streetLampStyle: 'incandescent',
    sidewalkStyle: 'cobblestone',
    pedestrianStyle: '60s',
    treeStyle: 'classic',
    fenceStyle: 'iron',
    billboardAdStyle: 'handpainted',
    particleType: 'none',
  },
  1985: {
    year: 1985,
    name: 'Neon Age',
    skyColor: [0.82, 0.85, 0.95],
    fogColor: [0.85, 0.86, 0.93],
    fogDensity: 0.008,
    ambientIntensity: 1.5,
    ambientColor: [0.80, 0.82, 0.90],
    sunIntensity: 3.0,
    sunColor: [1.0, 0.95, 0.85],
    sunPosition: [25, 15, 30],
    groundColor: [0.60, 0.60, 0.63],
    roadColor: [0.40, 0.40, 0.44],
    buildingStyle: 'neon',
    hasSnow: false,
    hasRain: false,
    hasFog: true,
    hasStars: false,
    starDensity: 0,
    hasFlying: false,
    hasHolograms: false,
    hasElectricVehicles: false,
    hasClassicCars: false,
    hasMilitaryVehicles: false,
    hasModernSedan: false,
    hasNeonSigns: true,
    hasDigitalBillboards: false,
    hasHolographicAds: false,
    streetLampStyle: 'fluorescent',
    sidewalkStyle: 'concrete',
    pedestrianStyle: '80s',
    treeStyle: 'classic',
    fenceStyle: 'steel',
    billboardAdStyle: 'neon',
    particleType: 'embers',
  },
  2005: {
    year: 2005,
    name: 'Digital Dawn',
    skyColor: [0.78, 0.85, 0.95],
    fogColor: [0.85, 0.87, 0.92],
    fogDensity: 0.005,
    ambientIntensity: 1.5,
    ambientColor: [0.82, 0.85, 0.92],
    sunIntensity: 3.0,
    sunColor: [1.0, 0.98, 0.92],
    sunPosition: [40, 35, 20],
    groundColor: [0.62, 0.65, 0.58],
    roadColor: [0.42, 0.42, 0.45],
    buildingStyle: 'digital',
    hasSnow: false,
    hasRain: false,
    hasFog: false,
    hasStars: false,
    starDensity: 0,
    hasFlying: false,
    hasHolograms: false,
    hasElectricVehicles: false,
    hasClassicCars: false,
    hasMilitaryVehicles: false,
    hasModernSedan: true,
    hasNeonSigns: false,
    hasDigitalBillboards: true,
    hasHolographicAds: false,
    streetLampStyle: 'led',
    sidewalkStyle: 'asphalt',
    pedestrianStyle: '2000s',
    treeStyle: 'modern',
    fenceStyle: 'steel',
    billboardAdStyle: 'digital',
    particleType: 'none',
  },
  2025: {
    year: 2025,
    name: 'Smart City',
    skyColor: [0.78, 0.85, 0.95],
    fogColor: [0.85, 0.87, 0.92],
    fogDensity: 0.004,
    ambientIntensity: 1.5,
    ambientColor: [0.82, 0.85, 0.95],
    sunIntensity: 3.0,
    sunColor: [1.0, 0.98, 0.95],
    sunPosition: [45, 40, 25],
    groundColor: [0.65, 0.67, 0.63],
    roadColor: [0.40, 0.42, 0.45],
    buildingStyle: 'modern',
    hasSnow: false,
    hasRain: false,
    hasFog: false,
    hasStars: false,
    starDensity: 0,
    hasFlying: false,
    hasHolograms: false,
    hasElectricVehicles: true,
    hasClassicCars: false,
    hasMilitaryVehicles: false,
    hasModernSedan: true,
    hasNeonSigns: true,
    hasDigitalBillboards: true,
    hasHolographicAds: false,
    streetLampStyle: 'smart',
    sidewalkStyle: 'smart',
    pedestrianStyle: 'modern',
    treeStyle: 'modern',
    fenceStyle: 'energy',
    billboardAdStyle: 'digital',
    particleType: 'data',
  },
  2055: {
    year: 2055,
    name: 'Future',
    skyColor: [0.80, 0.88, 0.98],
    fogColor: [0.85, 0.88, 0.95],
    fogDensity: 0.003,
    ambientIntensity: 1.5,
    ambientColor: [0.80, 0.85, 0.95],
    sunIntensity: 3.0,
    sunColor: [0.9, 0.95, 1.0],
    sunPosition: [50, 45, 30],
    groundColor: [0.60, 0.62, 0.68],
    roadColor: [0.40, 0.42, 0.48],
    buildingStyle: 'futuristic',
    hasSnow: false,
    hasRain: false,
    hasFog: true,
    hasStars: true,
    starDensity: 0.8,
    hasFlying: true,
    hasHolograms: true,
    hasElectricVehicles: true,
    hasClassicCars: false,
    hasMilitaryVehicles: false,
    hasModernSedan: false,
    hasNeonSigns: true,
    hasDigitalBillboards: true,
    hasHolographicAds: true,
    streetLampStyle: 'holographic',
    sidewalkStyle: 'energy',
    pedestrianStyle: 'futuristic',
    treeStyle: 'bio',
    fenceStyle: 'energy',
    billboardAdStyle: 'holographic',
    particleType: 'aurora',
  },
};
