import type { EraInfo } from './types';
import { ERA_ORDER, type EraKey } from './types';

const eras: Record<EraKey, EraInfo> = {
  '1945': {
    year: 1945,
    name: 'Post-War America',
    description: 'The dawn of a new era after WWII. Simple brick buildings, vintage cars, and hopeful optimism.',
    skyTop: '#1a1a3e',
    skyBottom: '#c4a882',
    fogColor: '#b8a088',
    fogDensity: 0.012,
    ambientIntensity: 0.4,
    sunIntensity: 0.8,
    sunColor: '#f0d0a0',
    groundColor: '#5a5a4a',
    roadColor: '#3a3a3a',
    sidewalkColor: '#8a8a7a',
    buildingBaseColors: ['#8B6F47', '#A0845C', '#7A6B55', '#9C8B6E'],
    windowEmissive: '#f5e6c8',
    neonAccent: '',
    vehicleStyle: 'vintage',
    pedestrianOutfit: 'formal',
    adTheme: 'newspaper',
    billboardContent: 'war_posters',
    treeType: 'elm',
    streetLightColor: '#ffcc66',
    specialEffects: [],
  },
  '1965': {
    year: 1965,
    name: 'Swinging Sixties',
    description: 'The space age arrives. Neon signs, diners, convertibles, and a cultural revolution blooms.',
    skyTop: '#1e3a5f',
    skyBottom: '#87CEEB',
    fogColor: '#a8c0d0',
    fogDensity: 0.008,
    ambientIntensity: 0.5,
    sunIntensity: 1.0,
    sunColor: '#fff4e0',
    groundColor: '#4a4a3a',
    roadColor: '#333333',
    sidewalkColor: '#9a9a8a',
    buildingBaseColors: ['#C4A882', '#D4C4A8', '#B8A080', '#E0D0B8'],
    windowEmissive: '#ffe4a0',
    neonAccent: '#ff3366',
    vehicleStyle: 'classic',
    pedestrianOutfit: 'mod',
    adTheme: 'neon',
    billboardContent: 'soft_drink',
    treeType: 'maple',
    streetLightColor: '#ffeebb',
    specialEffects: ['neon_flicker'],
  },
  '1985': {
    year: 1985,
    name: 'The Neon Age',
    description: 'Dusk falls on glass towers. Arcades, synthwave aesthetics, and the birth of the digital age.',
    skyTop: '#0a0020',
    skyBottom: '#ff4488',
    fogColor: '#2a1040',
    fogDensity: 0.015,
    ambientIntensity: 0.2,
    sunIntensity: 0.6,
    sunColor: '#ff66aa',
    groundColor: '#2a2a2a',
    roadColor: '#222222',
    sidewalkColor: '#555555',
    buildingBaseColors: ['#2a2a3a', '#3a3a4a', '#1a1a2a', '#4a4a5a'],
    windowEmissive: '#44aaff',
    neonAccent: '#ff00ff',
    vehicleStyle: 'sporty',
    pedestrianOutfit: '80s',
    adTheme: 'arcade',
    billboardContent: 'synthwave',
    treeType: 'palm',
    streetLightColor: '#6644ff',
    specialEffects: ['neon_flicker', 'scanlines'],
  },
  '2005': {
    year: 2005,
    name: 'Y2K Boom',
    description: 'Glass condos rise. Digital billboards, SUVs everywhere, and the internet changes everything.',
    skyTop: '#334466',
    skyBottom: '#aabbdd',
    fogColor: '#8899aa',
    fogDensity: 0.01,
    ambientIntensity: 0.55,
    sunIntensity: 1.1,
    sunColor: '#ffffff',
    groundColor: '#555555',
    roadColor: '#2a2a2a',
    sidewalkColor: '#aaaaaa',
    buildingBaseColors: ['#667788', '#778899', '#556677', '#8899aa'],
    windowEmissive: '#ddeeff',
    neonAccent: '#00aaff',
    vehicleStyle: 'modern',
    pedestrianOutfit: 'casual_2000s',
    adTheme: 'digital',
    billboardContent: 'smartphone',
    treeType: 'oak',
    streetLightColor: '#ffffff',
    specialEffects: [],
  },
  '2025': {
    year: 2025,
    name: 'Green Future',
    description: 'LED facades, vertical gardens, electric vehicles, and sustainable urban living.',
    skyTop: '#224466',
    skyBottom: '#88ccdd',
    fogColor: '#99aabb',
    fogDensity: 0.006,
    ambientIntensity: 0.6,
    sunIntensity: 1.2,
    sunColor: '#ffffff',
    groundColor: '#4a5a4a',
    roadColor: '#222222',
    sidewalkColor: '#bbbbbb',
    buildingBaseColors: ['#88aa88', '#669966', '#77aa77', '#99bb99'],
    windowEmissive: '#aaffcc',
    neonAccent: '#00ff88',
    vehicleStyle: 'electric',
    pedestrianOutfit: 'tech_casual',
    adTheme: 'eco',
    billboardContent: 'sustainability',
    treeType: 'birch',
    streetLightColor: '#aaffcc',
    specialEffects: ['green_glow'],
  },
  '2055': {
    year: 2055,
    name: 'Megastructure Era',
    description: 'Supertall holographic megastructures. Flying vehicles, AI governance, and the city reaches for the stars.',
    skyTop: '#000011',
    skyBottom: '#001133',
    fogColor: '#001122',
    fogDensity: 0.004,
    ambientIntensity: 0.15,
    sunIntensity: 0.3,
    sunColor: '#4488ff',
    groundColor: '#111122',
    roadColor: '#0a0a1a',
    sidewalkColor: '#222233',
    buildingBaseColors: ['#1a1a2e', '#0f0f1e', '#16162a', '#1e1e36'],
    windowEmissive: '#00ccff',
    neonAccent: '#00ffff',
    vehicleStyle: 'flying',
    pedestrianOutfit: 'futuristic',
    adTheme: 'holographic',
    billboardContent: 'mars_colony',
    treeType: 'crystal',
    streetLightColor: '#00ffff',
    specialEffects: ['hologram', 'particle_rain', 'flight_paths'],
  },
};

export function getEra(key: EraKey): EraInfo {
  return eras[key];
}

export function getAllEras(): EraInfo[] {
  return ERA_ORDER.map(k => eras[k]);
}

export function lerpEra(from: EraInfo, to: EraInfo, t: number): Partial<EraInfo> {
  return {
    skyTop: to.skyTop,
    skyBottom: to.skyBottom,
    fogColor: to.fogColor,
    fogDensity: from.fogDensity + (to.fogDensity - from.fogDensity) * t,
    ambientIntensity: from.ambientIntensity + (to.ambientIntensity - from.ambientIntensity) * t,
    sunIntensity: from.sunIntensity + (to.sunIntensity - from.sunIntensity) * t,
    sunColor: to.sunColor,
    groundColor: to.groundColor,
    roadColor: to.roadColor,
    sidewalkColor: to.sidewalkColor,
    buildingBaseColors: to.buildingBaseColors,
    windowEmissive: to.windowEmissive,
    neonAccent: to.neonAccent,
    vehicleStyle: to.vehicleStyle,
    pedestrianOutfit: to.pedestrianOutfit,
    adTheme: to.adTheme,
    billboardContent: to.billboardContent,
    treeType: to.treeType,
    streetLightColor: to.streetLightColor,
    specialEffects: to.specialEffects,
  };
}
