import type { EraDescriptor, EraId } from './types';

/**
 * Era table. Each entry is crafted so adjacent eras differ across every visible
 * axis: silhouette, window pattern, vehicles, pedestrian outfits, signage and
 * sky/fog tint. Colors are intentionally distinct.
 */
export const ERAS: Record<EraId, EraDescriptor> = {
  '1945': {
    id: '1945',
    year: 1945,
    label: 'Post-War',
    skyTop: '#9db4c4',
    skyBottom: '#d8c7a8',
    fogColor: '#c4b79d',
    fogDensity: 0.012,
    sunColor: '#fff0d0',
    sunIntensity: 1.15,
    ambientColor: '#b9b0a0',
    ambientIntensity: 0.7,
    groundColor: '#5b554c',
    sidewalkColor: '#8a8278',
    facadeColor: '#7d6f5a',
    windowColor: '#ffd98a',
    windowLitChance: 0.22,
    silhouette: 'flat',
    typicalFloors: 5,
    vehicles: ['car'],
    pedestrianColors: ['#3a4a66', '#6b4a3a', '#4a4a4a', '#5a3a3a'],
    storefronts: [
      { name: 'Apollo Diner', floor: 0 },
      { name: 'Victory Bakery', floor: 0 },
      { name: 'General Store', floor: 0 },
      { name: 'Tailor & Sons', floor: 0 },
    ],
    billboard: 'BUY WAR BONDS',
    seed: 19450101,
  },
  '1965': {
    id: '1965',
    year: 1965,
    label: 'Space Age',
    skyTop: '#7fa8d6',
    skyBottom: '#cfe3f2',
    fogColor: '#bcd2e0',
    fogDensity: 0.01,
    sunColor: '#fff4e0',
    sunIntensity: 1.25,
    ambientColor: '#aab8c4',
    ambientIntensity: 0.72,
    groundColor: '#494f57',
    sidewalkColor: '#9aa0a8',
    facadeColor: '#b8a890',
    windowColor: '#ffdfa0',
    windowLitChance: 0.28,
    silhouette: 'stepped',
    typicalFloors: 8,
    vehicles: ['car', 'truck'],
    pedestrianColors: ['#c0392b', '#e67e22', '#2c3e50', '#ecf0f1', '#8e44ad'],
    storefronts: [
      { name: 'Go-Go Lounge', floor: 0 },
      { name: 'Auto-Mat', floor: 0 },
      { name: 'Rocket Records', floor: 0 },
      { name: 'Space-Age Diner', floor: 0 },
    ],
    billboard: 'THE FUTURE IS NOW',
    seed: 19650202,
  },
  '1985': {
    id: '1985',
    year: 1985,
    label: 'Neon Boom',
    skyTop: '#3a3a6a',
    skyBottom: '#8a4a7a',
    fogColor: '#5a3a5a',
    fogDensity: 0.018,
    sunColor: '#ff9ad0',
    sunIntensity: 0.9,
    ambientColor: '#7a5a8a',
    ambientIntensity: 0.8,
    groundColor: '#2e2e34',
    sidewalkColor: '#6a6a72',
    facadeColor: '#3a3a44',
    windowColor: '#ff5ad0',
    windowLitChance: 0.4,
    silhouette: 'setback',
    typicalFloors: 12,
    vehicles: ['car', 'truck'],
    pedestrianColors: ['#ff2d95', '#00e5ff', '#ffe600', '#9b59b6', '#e74c3c', '#2ecc71'],
    storefronts: [
      { name: 'ARCADE PALACE', floor: 0 },
      { name: 'VIDEO HUT', floor: 0 },
      { name: 'NEON NAILS', floor: 0 },
      { name: 'CYBER CAFE', floor: 0 },
    ],
    billboard: 'TALK IS CHEAP. CALL NOW.',
    seed: 19850303,
  },
  '2005': {
    id: '2005',
    year: 2005,
    label: 'Digital',
    skyTop: '#5a6a8a',
    skyBottom: '#a0b0c8',
    fogColor: '#8a98ac',
    fogDensity: 0.013,
    sunColor: '#eaf2ff',
    sunIntensity: 1.1,
    ambientColor: '#90a0b4',
    ambientIntensity: 0.78,
    groundColor: '#3c3c40',
    sidewalkColor: '#8c8c92',
    facadeColor: '#6a7080',
    windowColor: '#9ad0ff',
    windowLitChance: 0.34,
    silhouette: 'glass',
    typicalFloors: 16,
    vehicles: ['car', 'truck'],
    pedestrianColors: ['#34495e', '#16a085', '#c0392b', '#7f8c8d', '#f1c40f', '#2c3e50'],
    storefronts: [
      { name: 'TechHub', floor: 0 },
      { name: 'Bean & Co', floor: 0 },
      { name: 'PhoneMart', floor: 0 },
      { name: 'GymZone', floor: 0 },
    ],
    billboard: 'GET ONLINE. 56k!',
    seed: 20050404,
  },
  '2025': {
    id: '2025',
    year: 2025,
    label: 'Eco-Future',
    skyTop: '#2a4a5a',
    skyBottom: '#6ad0b0',
    fogColor: '#4a8a8a',
    fogDensity: 0.009,
    sunColor: '#e0fff0',
    sunIntensity: 1.2,
    ambientColor: '#6aa0a0',
    ambientIntensity: 0.82,
    groundColor: '#2c3438',
    sidewalkColor: '#7ea890',
    facadeColor: '#4a7a6a',
    windowColor: '#7affd0',
    windowLitChance: 0.3,
    silhouette: 'glass',
    typicalFloors: 22,
    vehicles: ['car'],
    pedestrianColors: ['#1abc9c', '#3498db', '#9b59b6', '#e67e22', '#ecf0f1', '#2c3e50'],
    storefronts: [
      { name: 'NeoBite', floor: 0 },
      { name: 'VertiFarm', floor: 0 },
      { name: 'VoltCharge', floor: 0 },
      { name: 'LoopWear', floor: 0 },
    ],
    billboard: 'NET ZERO BY 2030',
    seed: 20250505,
  },
};

/** Ordered list of era descriptors (1945 -> 2025). */
export const ERA_LIST: EraDescriptor[] = Object.values(ERAS);
