import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {ERAS,EraId} from './eras';
import {SfxMixer} from './audio/mixer';
import './style.css';

const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<header><div class="brand"><b>CHRONICLE</b><span>URBAN TIME STUDY / 1945—2055</span></div><div class="readout"><strong id="year">1945</strong><span id="eraName">POST-WAR MODERN</span></div><button id="sound">◉ SOUND</button><button id="play">▶ PLAY</button><button id="loop">↻ LOOP</button></header><section class="timeline"><div class="ticks" id="ticks"></div><input id="slider" type="range" min="0" max="5" value="0" step="1" aria-label="City era"/><div class="progress"></div></section><aside id="info"><small>BUILDING PROFILE</small><h2>Click a building</h2><p>Explore the block to reveal its story.</p></aside><div id="hint">DRAG TO ORBIT　RIGHT DRAG TO PAN　SCROLL TO ZOOM</div>`;
const ticks=document.querySelector('#ticks')!; ERAS.forEach((e,i)=>{const d=document.createElement('div');d.innerHTML=`<b>${e.year}</b><small>${e.label}</small>`;d.dataset.i=String(i);ticks.append(d)});
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.outputColorSpace=THREE.SRGBColorSpace;app.append(renderer.domElement);
const scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,300);camera.position.set(25,19,27);scene.fog=new THREE.Fog(ERAS[0].fog.color,25,125);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,4,0);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.47;controls.minDistance=10;controls.maxDistance=65;
const hemi=new THREE.HemisphereLight(0xffdfc0,0x202b39,1.7), sun=new THREE.DirectionalLight(0xffd6aa,2.4);sun.position.set(15,28,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(hemi,sun);
const world=new THREE.Group();scene.add(world);const ray=new THREE.Raycaster(), pointer=new THREE.Vector2();let eraIndex=0, targetIndex=0, playing=false, looping=false, last=performance.now(), playTime=0;const mixer=new SfxMixer();controls.autoRotateSpeed=.35;
const skyMaterial=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color(ERAS[0].sky.top)},bottom:{value:new THREE.Color(ERAS[0].sky.bottom)}},vertexShader:'varying vec3 v;void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform vec3 top;uniform vec3 bottom;varying vec3 v;void main(){float h=clamp(normalize(v).y*.5+.5,0.,1.);gl_FragColor=vec4(mix(bottom,top,h),1.);}'});
scene.add(new THREE.Mesh(new THREE.SphereGeometry(145,32,16),skyMaterial));
const mat=(color:string,rough=.8)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:rough<.4?.7:.05});
function setWorldOpacity(opacity:number){world.traverse(object=>{const mesh=object as THREE.Mesh;const materials=Array.isArray(mesh.material)?mesh.material:(mesh.material?[mesh.material]:[]);materials.forEach(material=>{material.transparent=opacity<1;material.opacity=opacity;});});}
function build(){world.clear();const e=ERAS[eraIndex], bs=e.buildingStyle;const ground=new THREE.Mesh(new THREE.PlaneGeometry(100,100),mat(e.groundTint));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;world.add(ground);
 const road=new THREE.Mesh(new THREE.BoxGeometry(11,.12,72),mat('#252b32'));road.position.y=.06;road.receiveShadow=true;world.add(road);for(let z=-34;z<35;z+=5){const dash=new THREE.Mesh(new THREE.BoxGeometry(.16,.03,2.1),mat('#d8c99c'));dash.position.set(0,.14,z);world.add(dash)}
 for(let side of [-1,1]){for(let i=0;i<5;i++){const x=side*(8+i%2*4),z=-25+i*12,h=bs.stories*1.7+(i%3)*1.2,w=bs.footprint+(i%2);const g=new THREE.Group();g.position.set(x,0,z);const body=new THREE.Mesh(new THREE.BoxGeometry(w,h,8),mat(bs.facadePalette[i%bs.facadePalette.length]));body.position.y=h/2;body.castShadow=true;body.receiveShadow=true;g.add(body);
   for(let floor=0;floor<bs.stories;floor++)for(let col=0;col<3;col++){const win=new THREE.Mesh(new THREE.BoxGeometry(1.05,.72,.05),mat(e.accentColor,.25));win.position.set(-w*.28+col*w*.28,1.2+floor*1.7,4.03);g.add(win)}
   const roof=new THREE.Mesh(new THREE.BoxGeometry(w*1.08,.3,8.2),mat(e.accentColor,.35));roof.position.y=h+.15;g.add(roof);const sign=new THREE.Mesh(new THREE.BoxGeometry(Math.min(w*1.2,6),.65,.1),mat(e.accentColor,.3));sign.position.set(0,1.25,4.1);g.add(sign);g.userData={building:true,name:e.storefrontSigns[i%3],style:bs.name};world.add(g);
 }}
 for(let i=0;i<14;i++){const x=(i%2?1:-1)*(2.4+(i%4)*.9),z=-31+i*4.7;const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.12,.18,1.8,6),mat('#49382f'));trunk.position.set(x,.9,z);const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(1.1+(i%3)*.2,1),mat(e.pedestrianPalette[i%3]));crown.position.set(x,2.2,z);world.add(trunk,crown)}
 for(let i=0;i<6;i++){const car=new THREE.Group();car.position.set(i%2?2.8:-2.8,-.0,-27+i*10);const base=new THREE.Mesh(new THREE.BoxGeometry(2.1,.55,3.8),mat(e.pedestrianPalette[i%3],.3));base.position.y=.55;car.add(base);const cab=new THREE.Mesh(new THREE.BoxGeometry(1.5,.55,1.65),mat(e.accentColor,.2));cab.position.y=1;car.add(cab);car.userData={vehicle:e.vehicleTypes[i%2]};world.add(car)} }
let transitionTime=1.4;
function transition(){const e=ERAS[targetIndex];(document.querySelector('#year') as HTMLElement).textContent=String(e.year);(document.querySelector('#eraName') as HTMLElement).textContent=e.label;document.body.style.setProperty('--accent',e.accentColor);targetIndex=Math.max(0,Math.min(5,targetIndex));eraIndex=targetIndex;build();setWorldOpacity(0);world.scale.setScalar(.96);transitionTime=0;scene.fog=new THREE.Fog(e.fog.color,22,120);hemi.color.set(e.ambient.color);sun.color.set(e.sun.color);sun.intensity=e.sun.intensity;sun.position.set(Math.cos(e.sun.azimuth)*28,e.sun.elevation*30,Math.sin(e.sun.azimuth)*28);skyMaterial.uniforms.top.value.set(e.sky.top);skyMaterial.uniforms.bottom.value.set(e.sky.bottom);mixer.setEra(e.id);}
function setIndex(i:number){if(i===eraIndex)return;targetIndex=i;transition();(document.querySelectorAll('.ticks div') as NodeListOf<HTMLElement>).forEach((x,n)=>x.classList.toggle('active',n===i));mixer.click()}
build();(document.querySelector('.ticks div') as HTMLElement).classList.add('active');
const slider=document.querySelector<HTMLInputElement>('#slider')!;slider.oninput=()=>setIndex(Number(slider.value));document.querySelectorAll('.ticks div').forEach((d,i)=>d.addEventListener('click',()=>{slider.value=String(i);setIndex(i)}));
document.querySelector('#sound')!.addEventListener('click',()=>{mixer.init();mixer.toggleMute();(document.querySelector('#sound') as HTMLElement).textContent=mixer.muted?'○ MUTED':'◉ SOUND'});document.querySelector('#play')!.addEventListener('click',()=>{mixer.init();playing=!playing;(document.querySelector('#play') as HTMLElement).textContent=playing?'Ⅱ PAUSE':'▶ PLAY'});document.querySelector('#loop')!.addEventListener('click',()=>{looping=!looping;(document.querySelector('#loop') as HTMLElement).classList.toggle('on',looping)});
addEventListener('keydown',e=>{if(e.key>='1'&&e.key<='6'){slider.value=String(+e.key-1);setIndex(+e.key-1)}if(e.code==='Space'){e.preventDefault();(document.querySelector('#play') as HTMLElement).click()}if(e.key.toLowerCase()==='m')(document.querySelector('#sound') as HTMLElement).click();if(e.key.toLowerCase()==='r')controls.autoRotate=!controls.autoRotate});
let pointerDownX=0,pointerDownY=0;renderer.domElement.addEventListener('pointerdown',e=>{mixer.init();pointerDownX=e.clientX;pointerDownY=e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-pointerDownX,e.clientY-pointerDownY)>6)return;const r=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(world.children,true).find(h=>h.object.userData.building);if(hit){const data=hit.object.userData;(document.querySelector('#info') as HTMLElement).innerHTML=`<small>BUILDING PROFILE / ${ERAS[eraIndex].year}</small><h2>${data.name}</h2><p>${data.style}. Era-specific materials, windows and street frontage.</p>`}});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
function frame(now:number){const delta=Math.min((now-last)/1000,.05);last=now;if(transitionTime<1.4){transitionTime=Math.min(1.4,transitionTime+delta);const t=transitionTime/1.4;setWorldOpacity(t);world.scale.setScalar(.96+.04*t)}if(playing){playTime+=delta;if(playTime>5.5){playTime=0;if(eraIndex===5&&!looping){playing=false;(document.querySelector('#play') as HTMLElement).textContent='▶ PLAY'}else{const n=eraIndex===5?0:eraIndex+1;slider.value=String(n);setIndex(n)}}}controls.update();renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);
